### ISSUE TITLE
Download page

### ISSUE THREAD

**Issue by ndhuygelaere** [OIEau/uwwtd#112]
tous les liens fonctionnels, un format de plus: kml, paragraphe d'intro corrigé, clarification sur le contenu des colonnes view/download de la section metadata (ouvre zip pour download), cellules invoke service avec xml centrées, liens exemple pour la plateforme générique ne fonctionnent pas, vérifier liens sur les autres plateformes

**Comment by vincentgode** [comment]
Tous les liens sont fonctionnels
La colonne Download lance le téléchargement du fichier, la colonne View l'ouvre dans un nouvel onglet.

Le téléchargement ne fonctionne qu'avec Firefox (>20.0), Chrome (>14.0), Edge (13.0) et Opera (15.0).
