### ISSUE TITLE
fiche treatment

### ISSUE THREAD

**Issue by ndhuygelaere** [OIEau/uwwtd#118]
title of graph to be added: incoming and discharged loads (t/year), the ? Is not visible for 2nd and 3rd treatment

**Comment by ndhuygelaere** [comment]
Benoit : "the ? Is not visible for 2nd and 3rd treatment", can you describe ?

**Comment by friboben** [comment]
fixed: it was the ? in each fiche for treatment plant describing what means 2nd and 3rd that was not visible in a previous version
