### ISSUE TITLE
WISE Soes

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#121]
The layer is the layer of monitoring stations. That's fine but what has been requested are the BOD ammonium orthophosphate, nitrate concentration layer.

**Comment by ndhuygelaere** [comment]
BOD & Ammonium layers are not availables in WMS
Ok for nitrate et orthophosphate

Layers were found here : http://water.discomap.eea.europa.eu/arcgis/rest/services/RiversLakesSoE

**Comment by Rakedjian** [comment]
Ok for nitrate and orthophosphate. Is it possible to have in the pop-up window the last four years related to the average concentration? 

There is a written in the webpage http://water.discomap.eea.europa.eu/arcgis/rest/services/RiversLakesSoE

BOD and Ammonium (WM). Does it mean that the development are only partial for these layers comparing to what is available for N and orthophosphates?

**Comment by ndhuygelaere** [comment]
For nitrate and orthophosphate we only have average concentration for 2011. For eg, for nitrate we have this kind of fields

<table class="mean-annual-nitrates-in-rivers-by-station-2011 wms-ol-table-result table-striped">
<caption>Mean annual nitrates in rivers by station 2011</caption>
 <thead><tr><th class="OBJECTID">OBJECTID</th><th class="Countrycode">Countrycode</th><th class="Country">Country</th><th class="NationalstationID">NationalstationID</th><th class="Longitude">Longitude</th><th class="Latitude">Latitude</th><th class="Year">Year</th><th class="Determinand">Determinand</th><th class="Unit">Unit</th><th class="Annualmeanvalue">Annualmeanvalue</th><th class="Classificationclass">Classificationclass</th> </tr></thead>
<tbody>
 <tr class="odd"><td class="OBJECTID">6112</td><td class="Countrycode">SI</td><td class="Country">Slovenia</td><td class="NationalstationID">4360</td><td class="Longitude">14.5892</td><td class="Latitude">46.3266</td><td class="Year">2011</td><td class="Determinand">Nitrate</td><td class="Unit">mg/l N</td><td class="Annualmeanvalue">0.3531</td><td class="Classificationclass">1</td> </tr>
</tbody>
</table>

For BOD and Ammonium, i think EEA just have forgotten to set the WMS layer and without this format i can't implement these layers on SIIF plateform.
