### ISSUE TITLE
Deadline third treatment

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#122]
When the agglomeration is below 10 000 p.e. or there is no discharge in a sensitive area there is no deadline for more string treatment. If we write a deadline we create a confusion

http://webnuxdev.rnde.tm.fr/uwwtd/agglomeration/ieag_327/2012

![capture](https://cloud.githubusercontent.com/assets/16286544/12198606/f4877762-b611-11e5-816c-0d9d36ac79b0.PNG)

**Comment by friboben** [comment]
The agglomeration is 10338pe hence above 10000pe, see also example http://webnuxdev.rnde.tm.fr/nd_uwwtd_si/agglomeration/si08203/2012

**Comment by friboben** [comment]
issue fixed
