### ISSUE TITLE
Hyperlink problem in the ressource

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#123]
I have tested the new resource webpage

Please replace the hyperlink and the name of the "Waste Water LIFE project" by "Water life project"
and the new hyperlink is the following
http://ec.europa.eu/environment/life/project/Projects/index.cfm?fuseaction=home.getProjects&themeID=75

The current hyperlink is related to air policy. I have certainly made a mistake

**Comment by ndhuygelaere** [comment]
I think you have given the right link but it's probably a bug on EEA website
because 77 is id of subtheme of waste water.
I have change the text
