### ISSUE TITLE
Article 17 exportation

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#125]
Je ne trouve plus l'endroit ou on peut prééditer le fichier de l'Article 17

**Comment by evincentoieau** [comment]
You can find it in the menu "Editorial menu" (visible when connected)
"Add Article 17 information"
then choose the year, submit, and you can download the file when you click on "Article 17 pre-filled file"

**Comment by Rakedjian** [comment]
Thanks I was not aware of the procedure
