### ISSUE TITLE
Title of the legend of the discharge point map

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#130]
As regards this new map it is better to have in the title of the legend "compliant of the UWWTP linked to the discharge points" or something like that.

**Comment by friboben** [comment]
Proposal: "Discharge points - Compliance map: compliance of load entering the treatment plant(s) connected to the discharge point"

**Comment by ndhuygelaere** [comment]
We use this text : "Compliance of the UWWTP linked to the discharge point by load entering and by receving area type"
