### ISSUE TITLE
Statitistic webpage

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#131]
Pb of visualisation of the graph

This is what I have currently on the development plateform of Ireland. No graph.
![visualisation stat](https://cloud.githubusercontent.com/assets/16286544/12576878/15dd86be-c417-11e5-98f9-cd6de8242add.PNG)

**Comment by ndhuygelaere** [comment]
Sory, we are going to update this page.
The last version is available on dev website : http://webnuxdev.rnde.tm.fr/uwwtd/
Graphs on  two last lines "Waste water treatement plant : Total load entering and discharged" and "MS level" are not avaible, but data table on back of flip card are ready.
You can now access to "All years" option on the select form item of year on the top of page.
