### ISSUE TITLE
color of the load agglomeration statistic graph

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#132]
Is it possible to change the color of the bars. It is not so easy to see the difference

Is it also possible to see somewhere the percentage

![loadgraphstatistic](https://cloud.githubusercontent.com/assets/16286544/12582487/c558819a-c43d-11e5-8c46-ff9d182aa372.PNG)

**Comment by friboben** [comment]
is this http://webnuxdev.rnde.tm.fr/nd_uwwtd_si/stats/graphs better?

**Comment by Rakedjian** [comment]
Yes
