### ISSUE TITLE
Ressources to resource

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#133]
In English there is no double s in resource

It has to be written resources.  Is is the best title for this kind of topic?

**Comment by friboben** [comment]
With the current content it could be written "useful links", do you agree?

**Comment by Rakedjian** [comment]
Yes

**Comment by friboben** [comment]
Proposal to enrich the section with 3 sub-sections, see detailed document here
[Resources.docx](https://github.com/OIEau/uwwtd/files/112456/Resources.docx)

**Comment by Rakedjian** [comment]
OK

**Comment by friboben** [comment]
files to use 
[Resources-v2.docx](https://github.com/OIEau/uwwtd/files/114013/Resources-v2.docx)
[Biblio-SIIF.zip](https://github.com/OIEau/uwwtd/files/114014/Biblio-SIIF.zip)

please note for page UWWTD SIIF Documents the point "•	The UWWTD SIIF concept paper" corresponds to above zip

**Comment by Rakedjian** [comment]
It is not a good idea to put here the SIIF concept paper because it is an old version of the SIIF concept and out dated.

It could be also perhaps better to change the order

Useful links
About the SIIF
SIIF for developpers 

propose in the delete the part related to the concept paper and the communication and to add a new part at the end of the submenu about the SIIF

"Background of the SIIF" and write the folowing

SIIF is also a way to implement two European directives, one Decision and at least six communications

European Directives
[2003/4/EC - on public access to environmental information](http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32003L0004&qid=1416830399380)
[2007/2/CE - establishing an Infrastructure for Spatial Information in the European Community (INSPIRE)](http://inspire.ec.europa.eu/)

European Decision
[Decision 1386/2013/EU on a General Union Environment Action Programme to 2020 "Living well, within the limits of our planet"](http://ec.europa.eu/environment/action-programme/)


European Communications
[COM (2008) 46 - Towards a Shared Environmental Information System (SEIS)](http://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:52008DC0046)
[COM (2008) 773 - on implementing European Community Environmental Law](http://ec.europa.eu/environment/legal/law/pdf/com_2008_773_en.pdf)
[COM (2010) 2020 - A strategy for smart, sustainable and inclusive growth](http://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1417082394583&uri=CELEX:52010DC2020)
[COM (2012) 95 - Improving the delivery of benefits from EU environment measures : building confidence through better knowledge and responsiveness](http://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1417082468133&uri=CELEX:52012DC0095)
[COM (2012) 673 - A Blueprint to Safeguard Europe's Water Resources](http://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1417082589797&uri=CELEX:52012DC0673)
[COM (2013) 685 - Regulatory Fitness and Performance (REFIT) : Results and Next ](http://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1417082637412&uri=CELEX:52013DC0695)

**Comment by friboben** [comment]
The concept paper is containing both the concept and the IT aspects of the interoperability key components, that is why I found it useful but OK. Could you please check the herewith and confirm this is what you mean? [Resources-v3.docx](https://github.com/OIEau/uwwtd/files/114264/Resources-v3.docx)

**Comment by friboben** [comment]
the version 3 is validated by Bruno (over phone) and can be implemented.

**Comment by ndhuygelaere** [comment]
fixed
