### ISSUE TITLE
distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#134]
I don't know if the Slovenian website has been updated with all the new functionalities.

As regards distance to compliance there is an issue related to pending deadlines situations. If the information is available the calculation has to be done. There is perhaps a need to change the color of the not compliant situation (orange instead of red)

In this situation we have a problem of lack of information concerning the treatment plant. It means that it is not possible to have 0 for secondary treatment. There is a need to write something like unknown.

http://webnuxdev.rnde.tm.fr/uwwtd_si/agglomeration/si20007/2012
![distancetocompliance](https://cloud.githubusercontent.com/assets/16286544/12650139/eec5fc24-c5e1-11e5-9845-ace871ab3945.PNG)

**Comment by friboben** [comment]
Could you please check the above link and here http://webnuxdev.rnde.tm.fr/uwwtd_si/agglomeration/si16481/2012
In the above, the secondary should be orange and I will ask for correction, but with orange we probably need a legend or something to state orange=pending deadline?

**Comment by Rakedjian** [comment]
There is a problem with this agglomeration because of the deadline written below. For Article 3, 4 and 5 the deadlines are 31/12/2015. It means that the color for not compliance concerning pending deadline has to be same. We know also that There were some problems of deadlines reported in Slovenia but the website has to be coherent with the deadline written. 
As regards the legend it could be perhaps youseful to add a legend for the table to explain on the one hand what is distance to compliance and on the other hand the color that is used. This is below my proposal as regards distance to compliance definition. 

The distance to compliance concept present the rate of waste water load that is: 
•	adequately connected to a centralised urban waste water collecting system or addressed via Individual or Appropriate System (IAS) 
and then when collected:
•	treated at an adequate level (secondary or more stringent treatment) as required by the directive,
•	and with the performance requirements under tables 1 or 2 of the annex I of  Directive 91/271/EEC, (UWWTD).

**Comment by friboben** [comment]
We propose to have it like for the connection compliance with a pop up window. Please find hereunder the proposed text (blue, red and grey are already identified and explained in the temporal line):
"The distance to compliance concept present the rate of waste water load that is: 
• adequately connected to a centralised urban waste water collecting system or addressed via Individual or Appropriate System (IAS) 
and then when collected:
• treated at an adequate level (secondary or more stringent treatment) as required by the directive,
• and with the performance requirements under tables 1 or 2 of the annex I of Directive 91/271/EEC, (UWWTD).
When countries joined the EU, they have obtained a delay to implement the Directive. In such case the deadline for implementing the above (see in section characteristics) may be different, and if the above is not already implemented for the agglomeration it is identified with orange colour in the table."

**Comment by Rakedjian** [comment]
OK

**Comment by bbondier** [comment]
This has been implemented.
