### ISSUE TITLE
Article 17 UWWTP

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#136]
See my comments in the file below
[Forward looking aspect UWWTP.docx](https://github.com/OIEau/uwwtd/files/108585/Forward.looking.aspect.UWWTP.docx)

**Comment by friboben** [comment]
for name of EU fund, the acronyms used by poland are in Polish (KS is for cohesion fund). It will be difficult for the tool to manage the translation of all acronyms in all languages, only what is reported can be made visible.

**Comment by Rakedjian** [comment]
Ok I understand. Don't change anything at this stage.

**Comment by ndhuygelaere** [comment]
fixed
