### ISSUE TITLE
homepage (recette)

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#138]
-	Titre dans la légende, remplacer NUTS par Administrative units (NUTS)
-	Ordre des nuts : 3, 2, 1, 0
-	Wise Soe : pas de légende pour les différentes couleurs + Bruno voulait les stations de monitoring pour 4-5 paramètres et pas la qualité générale
-	Texte sous la carte « …These agglomerations generated a total load of 5 164 016 (p.e)…. » enlever les parenthèses à (p.e) « …These agglomerations generated a total load of 5 164 016 p.e…. »
-	Pop up « About the SIIF project at the origin of this IT development »: changer le titre quand la popup s’ouvre pour avoir le même titre et changer le texte (cf fichier joint)
-	Bas de page :
o	Lien Directorate General Environment : si possible ouvrir dans une fenêtre séparée
o	Modifier le texte « Expanding the Urban Wastewater Structured Information and Implementation Framework (SIIF) – n°: 07.0201/2014/SFRA/698614/ENV.C.2  en “Expanding the Urban Wastewater Treatment Directive Structured Implementation and Information Framework (UWWTD SIIF) – n°: 07.0201/2014/SFRA/698614/ENV.C.2 and n°07.0201/2014/SFRA/698614/ENV.C.2”
o	Credits : changer le texte
o	Disclaimer : modifier le début du texte
éléments pour modifier les textes ici:
[homepage-pages-modifications.docx](https://github.com/OIEau/uwwtd/files/114024/homepage-pages-modifications.docx)

**Comment by ndhuygelaere** [comment]
Vincent : je me garde la partie concernant les NUTS. Une fois les autres points traités réassigne moi les bugs

**Comment by ndhuygelaere** [comment]
Ok point 1, 2, 3. But NUTS are sort in this order 0,1,2,3

**Comment by vincentgode** [comment]
Points 4, 5 et 6 Ok.
