### ISSUE TITLE
page view/discover (recette)

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#139]
-	Mettre à la racine la page fourni
[view-discover-v2.docx](https://github.com/OIEau/uwwtd/files/114027/view-discover-v2.docx)
-	Page agglomeration compliance : 
o	Carte : 3 base layer comme sur la page d’accueil et dans le même ordre doivent suffire. Le niveau Nuts 3 est quasi invisible : il faudrait untrait plus épais et/ou une autre couleur
o	trier le tableau par charge décroissante  (generated load) plutôt que nom
o	fonction print : ce serait bien d’avoir un numéro de page et un entête de page à chaque page qui suit la page de titre, avec le titre du doc et la date de production
o	chiffres des tableaux derrière les graphes avec alignement à droite
-	page agglomeration connection
o	idem agglomeration compliance 
-	page treatment plant compliance
o	idem agglomeration compliance 
o	titre Global compliance pour le critère de tri dédié
-	page treatment plant treatment
o	idem agglomeration compliance 
-	page treatment plant pressure
o	idem agglomeration compliance 
o	ordre des critères de tri : nuts et RBD juste avant article 17
o	la couche COD devrait être en dessous du titre UWWTD
-	page agglomeration individuelle : le menu n’est plus cliquable quand on est sur la page (ex : http://webnuxdev.rnde.tm.fr/uwwtd/agglomeration/ieag_82/2012)
-	page treatment plant individuelle : si possible resserrer les lignes du paragraphe treatment performance
-	page receiving area : n’y avait-il pas une révision en cours de la mise en page ?

**Comment by ndhuygelaere** [comment]
Vincent : il est possible que certains points soient déjà résolus

**Comment by vincentgode** [comment]
Les points suivants sont ok :
Mettre à la racine la page fourni view-discover-v2.docx
page agglomeration individuelle : le menu n’est plus cliquable quand on est sur la page 
page treatment plant individuelle : si possible resserrer les lignes du paragraphe treatment performance

**Comment by ndhuygelaere** [comment]
page receiving area : --> bug #154 
page treatment plant pressure : OK
page treatment plant compliance : filter label : OK
Page agglomeration compliance
- base layer : ok,
- nuts 3 : ok (gris plus foncé),
- default sort --> bug #155
- print --> bug #156
