### ISSUE TITLE
Sur la page "Agglomeration -> treatment map", le camembert semble incorrect

### ISSUE THREAD

**Issue by lcrespin** [OIEau/uwwtd#14]
Sur la page "Agglomeration -> treatment map", le camembert semble incorrect puisqu'il ne pondère pas les rejets par rapport au Generated Load de l'agglo.

Il faudrais en rajouter un deuxieme pondéré par Generated Load

**Comment by ndhuygelaere** [comment]
ok, colonne de données changée
