### ISSUE TITLE
page Download/invoke (recette)

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#140]
-	tableau data :
o	le premier xml renvoi à la page d’accueil et pas au fichier
o	les lignes discharge point et sensitive area sont buggées
-	tableau metadata :
o	la colonne download ouvre le fichier xml au lieu de le charger en zip
-	tableau services : le tableau dépasse la largeur standard de page

**Comment by ndhuygelaere** [comment]
Pour le point 2 je ne pense pas qu'on puisse y faire grand chose.
Vincent : regarde donc points 1 & 3

**Comment by vincentgode** [comment]
Les points 1 et 3 sont ok. Je n'ai cependant pas constaté le point "les lignes discharge point et sensitive area sont buggées". Le fichier .xml contient des données <DischargePoint>. Pourriez vous m'indiquer ce qui ne convient pas ?
Merci

**Comment by ndhuygelaere** [comment]
je penqe qu'il manque les fichiers XML de données dans les répertoires /default/files/ pour au moins un des sites de recette ou de prod

**Comment by friboben** [comment]
voir par exemple ici: http://www.uwwtd.oieau.fr/services/ows/?service=WFS&version=1.1.0&request=GetFeature&typeName=UWWTD:UWWTD:UWWTD_Ireland_DischargePoint&CQL_FILTER=UWWTD:repReportedPerdiod=2012
tous les liens des 2 lignes du tableau de download renvoient le même type d'erreur.

**Comment by ndhuygelaere** [comment]
Ok already fix by me in a previous iteration, so i can close the issue
