### ISSUE TITLE
page View stats (recette)

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#141]
-	alignement des chiffres à droite si possible pour tous les tableaux
-	all years :
o	tableau pour generated load by collection type : le total est sur 2 lignes : peut être agrandir un peu la colonne ( ?)
o	tableau generated load by sewage network type : peut être mettre l’astérisque aussi dans le tableau?
o	pour tous les graphes de load (agglomeration generated load et waste water treatment plant load enteringajouter l’unité dans le titre (population equivalent – p.e.)
o	pour MS level sludge destination mettre pour le * « * : Tons of Dry Substance per year T DS/year »

**Comment by ndhuygelaere** [comment]
MS level sludge : OK
