### ISSUE TITLE
distance to compliance graphs

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#142]
There is a prb of legend Red has to be for Not compliant situation

There is another pb with Article 5. The target as regards article 5 has to be the load connecte that need a more stringent treatment and not the total load connected. It means that it is not possible to have the same amount of p.e. than for article 4.

It is also better to change the titles and to speak about connection, secondary treatment and more stringent treatment and not Article 3, 4 and 5.

![distance to compliance graph](https://cloud.githubusercontent.com/assets/16286544/12776930/e0635d1c-ca59-11e5-8410-f8e1aadfef85.PNG)

**Comment by ndhuygelaere** [comment]
fixed
