### ISSUE TITLE
Slovenia Article 17 UWWTP

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#143]
I have not found such a deadline in the Article 17 report. Is there a specific problem with the calculation,

http://webnuxdev.rnde.tm.fr/uwwtd_si/treatment-plant/si_kcn_00045/2012

![sloveniaarticle 17 uwwtp](https://cloud.githubusercontent.com/assets/16286544/12777123/20d3d2ea-ca5b-11e5-8376-986010017ad4.PNG)

**Comment by friboben** [comment]
Not sure to understand the point on deadline. In Art17 reporting in sheet uwwtp, MS have to report "Date or expected date of completion of works" & "Expected date of compliance (12 months of compliant samples)" the figures here are only those entered by the MS when reporting in 2014, not deadlines. Can you clarify your question?

**Comment by Rakedjian** [comment]
The question is only about the date (or deadline) 09 February 2036 which is amazing. Does it really belong to the file reported?
This date is a deadline for me but of course not the official deadline of the directive.

**Comment by friboben** [comment]
There is an issue with the file imported, the deadline was reported 2013 and 2015: we check and reimport the file.

**Comment by friboben** [comment]
The fields are of the form MM/YYYY, the import tool seems to attribute wrong dates, probably format not suited: to be corrected.
