### ISSUE TITLE
Pb of visuation of Pop up window NUTS and RB in the SI website

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#144]
This is what i see

![popupwindowsi website pb](https://cloud.githubusercontent.com/assets/16286544/12777219/b7683106-ca5b-11e5-9eca-d21a3dda8bab.PNG)

and no more information

**Comment by ndhuygelaere** [comment]
La conf est ici : http://webnuxdev.rnde.tm.fr/nd_uwwtd_si/admin/config/system/proxy

il doit y avoir une erreur dans la fonction de mise à jour uwwtd_update_7126 dans le fichier d'install
