### ISSUE TITLE
hyperlink to Slovenian website in the other link webpage

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#145]
There is the wrong hyperlink because when we click on the Slovenian website it opens the Romanian website

**Comment by ndhuygelaere** [comment]
can you give us the url/page where the bug happen ?

**Comment by Rakedjian** [comment]
http://uwwtd.oieau.fr/slovenia/content/useful-links

**Comment by Rakedjian** [comment]
But also in all platforms
http://uwwtd.oieau.fr/content/useful-links

**Comment by ndhuygelaere** [comment]
fixed
