### ISSUE TITLE
title of the right pie in the UWWTP compliant webpage

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#147]
There is the wrong title of the pie

http://uwwtd.oieau.fr/slovenia/uwwtps/compliance

It is not treatment type in place but global compliance by load entering

![pieiuwwtpcompliance](https://cloud.githubusercontent.com/assets/16286544/12787013/de703ba8-ca93-11e5-968c-de324f866e38.PNG)

**Comment by ndhuygelaere** [comment]
fixed
