### ISSUE TITLE
Article 17 UWWTP list

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#148]
Where are all the treatment plants

when we put yes as regards Article 17 we only have a few points on the map as the list is much more longer; It seems that the information from Article 17 concerning pending deadline has not been integrated in the website. It is the excel file in the table below the table concerning expired deadline for agglomerations and for treatment plants

http://uwwtd.oieau.fr/slovenia/uwwtps/compliance?field_anneedata_value=2012&field_uwwloadenteringuwwtp_value_op=%3C&field_uwwloadenteringuwwtp_value%5Bvalue%5D=&field_uwwtreatmenttype_value=All&field_uwwcompliance_value=All&field_regionnuts_value=All&rbd=All&field_uwwbod5perf_value=All&field_uwwcodperf_value=All&field_uwwntotperf_value=All&field_uwwptotperf_value=All&field_article17_uwwtp_value_art=1&=Apply

**Comment by ndhuygelaere** [comment]
Some cells in excel file need to fill. In default case add a "-" character in empty cell
