### ISSUE TITLE
Explanation missing for connection, IAS, discharges without treatment

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#151]
Didn't I provide proposal related to the definition of theses parameters

![legendagglo](https://cloud.githubusercontent.com/assets/16286544/12886704/94e09502-ce6f-11e5-96d2-8ed6ec14f2df.PNG)

**Comment by friboben** [comment]
No, I do not think, I can not find back any file or text related to that.

**Comment by ndhuygelaere** [comment]
We can use provided definitions in the XSD file : 
* CS : Rate of generated load of agglomeration collected through collecting system (% of p.e.)
* IAS  : Rate of generated load of agglomeration addressed through IAS (% of p.e.)
* DWT : Rate of generated load of agglomeration not collected through collecting systems and not addressed through IAS (% of p.e.)

Do you agree with it ?

**Comment by friboben** [comment]
These are validated terms so this is perfect.

**Comment by Rakedjian** [comment]
I have to change it because we can not say IAS are IAS. I have to check what i already sent because i think that i already made a proposal on that.
