### ISSUE TITLE
Number format when downloading excel or CSV in the agglomeration map

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#153]
This has to be checked in any files generated. The number format of the donwloaded xls or csv has to be in number and not in text. This is important if we want to use the excel file and to make calculations with it. 

http://webnuxdev.rnde.tm.fr/uwwtd/agglomerations/compliance

![csvexceldonwload](https://cloud.githubusercontent.com/assets/16286544/12890279/512baf2c-ce83-11e5-99a8-5758b7b0c090.PNG)

![numberformat](https://cloud.githubusercontent.com/assets/16286544/12890286/552803b4-ce83-11e5-91b1-83ea80234397.PNG)

**Comment by vincentgode** [comment]
All xls columns are now designed to allow calculations.
