### ISSUE TITLE
page receiving area

### ISSUE THREAD

**Issue by ndhuygelaere** [OIEau/uwwtd#154]
update this page with content provide by bruno

**Comment by vincentgode** [comment]
Les points suivants ont été traités :
- Ajout des légendes (points d'interrogations)
- Ajout d'un cadre Related sensitive aeras lorsque cette information est disponible
- Modification de wording
- Ajout du cadre Description avec ces données légendées
- Ajout de la time line
- Correction de l'affichage de la map
- Ajout d'un lien dans l'info bulle de la sensitive aera qui redirige l'utilisateur sur l'accueil avec la map centrée et zoomée sur la sensitive aera
