### ISSUE TITLE
Renvois vers la page principale 

### ISSUE THREAD

**Issue by lcrespin** [OIEau/uwwtd#16]
Vu en Roumanie, mentioné par BR

BR souhaiterait que la google map sur une agglo ou treatment plant puisse renvoyer sur la page principale avec un zoom sur cette agglo/station pour la localiser par rapport aux autres agglo/station (suggestion à clarifier)

**Comment by ndhuygelaere** [comment]
fonction mise en place en cliquant sur les coordonnées X,Y sur les différenets fiches (ajout du control permalink)
