### ISSUE TITLE
SA register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#161]
When there is 0 in a designation criteria cell there is no designation date

![registre sa](https://cloud.githubusercontent.com/assets/16286544/13003169/3604fb88-d174-11e5-8384-a641435f9244.PNG)

**Comment by friboben** [comment]
Do you want to have "NO" in the cell or an empty cell or ?

**Comment by Rakedjian** [comment]
is its better to have an empty cell

**Comment by bbondier** [comment]
Done
