### ISSUE TITLE
Register UWWTP compliance article 4 SI

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#163]
It si not possible to have NC in the treatment type for Article 4, C for performance article 4 and C for final compliance in the "Compliance of treatment plant under expired and pending deadline"
In the situation of "SI_SLOVENSKI JAVORNIK_3556" and the UWWTP "UWWTP_JESENICE" there is a secondary treatment in place. In means that the treatement type is compliant. We have to find C and not NC in the treatment type cell.

There is the same problem in the "Compliance of treatment plant under expired deadline"

![register uwwtp compliance article 4](https://cloud.githubusercontent.com/assets/16286544/13004145/f6ae1806-d179-11e5-8492-54ce0c3b267d.PNG)

**Comment by friboben** [comment]
Agree, has to be checked and corrected

**Comment by friboben** [comment]
column AX has to consider only treatment type in place contains 2 and if yes, then treatment type =C
column AZ has to consider column AX and AY and if at least one is NC, then AZ= NC

**Comment by bbondier** [comment]
Fixed
