### ISSUE TITLE
REGISTER UWWTP compliance SI

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#164]
In the case of SI_BOVEC *_2873 agglomeration and the UWWTP 'UWWTP_BOVEC' we have NR and  NR in the treatment type and monitoring and C for the final result under article 4 and PD for the final result under Article 5. It is an agglomeration that is below 2000 p.e. and that is no more active. How is the algorithm calculated to obtain this result. We know that there is a secondary treatment and the performance are good but we know also that this agglomeration is not concerned by Article 5 due to the size.

![register uwwtp nr](https://cloud.githubusercontent.com/assets/16286544/13004524/3959c7b6-d17c-11e5-9ddb-7e3d20a965bf.PNG)

**Comment by friboben** [comment]
1. You asked to have also inactive even if not visible on the platform.
2. We use the same rule as on the platform, when compliant even if deadline not passed it is stated compliant and when not compliant if deadline not passed it is stated PD. However here there are some problems: a) we should add a criteria in art5 to only check if >=10000pe and put NR if below. in art4 to only check if >=2000pe and put NR if below.
b) the compliance check for column AZ and BC should state NR when treatment required is "appropriate"

**Comment by Rakedjian** [comment]
I want to understand. It is already written inactive and it is fine to know the situation as regards the different articles but it is not clear to me why we don't put C and C for treatment and performance instead of NR and NR concerning Article 4.

As regards Article 5 it is in this case not relevant.

**Comment by friboben** [comment]
Here as in all cases the treatment is assessed against the treatment required. As the treatment required here is "appropriate" it is not possible to decide if the treatment is place is compliant. We could refine the rules in next contract if needed, but it is not possible to do better with the current algorithms.

**Comment by bbondier** [comment]
Should we close this issue then?
