### ISSUE TITLE
REGISTER SI AGGLO nbr of UWWTPs

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#166]
It is strange to have zero in most of the cells as regards the parameter "Number of UWWTPs/ Collecting systems without treatment serving the agglomeration"

For most of these agglomerations there is at least a UWWTPs or a collecting system without treatment

![register agglo nb uwwtps](https://cloud.githubusercontent.com/assets/16286544/13011540/89613ec6-d1a7-11e5-8ec9-ea0ca277aa96.PNG)

**Comment by friboben** [comment]
This is in table Agglomeration of the register. Best to fill it is to count field "uwwCode" in table UWWTP for each of the agglomerations.

**Comment by bbondier** [comment]
Fixed
