### ISSUE TITLE
REGISTER SI UWWTP SA starting date of application 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#168]
The date that is in the starting data of application cel has not to be the same than the date of designation. 

![register si sa starting date of application](https://cloud.githubusercontent.com/assets/16286544/13012837/3dad112a-d1ad-11e5-837c-2d2254887ab7.PNG)

**Comment by friboben** [comment]
fixed, date of application not in xml file, hence not indicated in register.
