### ISSUE TITLE
REGISTER SI AGGLO pending deadline hierarchical approach

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#169]
We have an issue with agglomerations that have a not expired deadline concerning article 5; It is not possible to have a NC situation in the hierarchical approach. It has to be PD. It will be certainly be corrected with the eleventh algorithm, isn't it?

![register uwwtd compliance article 5 hierarchical](https://cloud.githubusercontent.com/assets/16286544/13013131/6f478d0e-d1ae-11e5-88d7-59e64c511a49.PNG)

**Comment by friboben** [comment]
is to be corrected. For art4 hierarchical, a correction is also to be introduced: when art3=PD art4 must be =PD and can not be NR

**Comment by bbondier** [comment]
Corrected
