### ISSUE TITLE
REGISTER summary table SI

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#170]
The content of the table is false. This is a table that is related to the hierarchical approach and that takes only into account agglomerations under expired deadline

There are lots of exemption due to transitional period that are totally not included in the table.

Compare the table from the register made by UBA and the new register

The SI total of each article has to be coherent with the number above. 

There is a need to update this register with what has been done with Ireland if we want to be sure that there is no other mistakes in the register.  Slovenia is a country that is representative of countries that have pending deadlines.

![register summary table](https://cloud.githubusercontent.com/assets/16286544/13013319/3ca5487c-d1af-11e5-8b4e-95fc75b76272.PNG)

register from the last reporting

![old register slovenia](https://cloud.githubusercontent.com/assets/16286544/13013315/37ca52ca-d1af-11e5-89ff-986e81d4e00a.PNG)

There is also a need to suppress decimals to have a more readable table.

**Comment by bbondier** [comment]
Fixed
