### ISSUE TITLE
Distance to compliance in the register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#172]
As regards the connection there is a little problem in some of the tables

as regards the graph sheet there is a need to write 0 as regards the not connected par and not 100

![distance to compliance statistics](https://cloud.githubusercontent.com/assets/16286544/13015305/a17eb66c-d1b8-11e5-99ff-502c0303f4f5.PNG)

In the distance to compliance sheet there is a need to write 0 and 0 as regards the distance to compliance collecting system in place and IAS. For the IAS 100% of the IAS meet the requirement and not 0%. It is the same with the total table.

![distance to compliance bis](https://cloud.githubusercontent.com/assets/16286544/13015343/c87f3f48-d1b8-11e5-9bd2-71e944f9469d.PNG)

As regards distance to compliance pending deadline it is 0 for all the cells and not an empty cell for connection and 100 for treatment

![distance to compliance pending deadline](https://cloud.githubusercontent.com/assets/16286544/13015388/0c661f24-d1b9-11e5-9dbd-7c9cc9ff1396.PNG)

**Comment by friboben** [comment]
sheet graphs, cell B105 put at 0
sheet distance to compliance cells E14, F14, E53, F53 put at 0
+ format excel sheet distance to compliance all cells in columns C and F number with no comma (format de cellule nombre, nombre de décimale = 0)

**Comment by bbondier** [comment]
Fixed
