### ISSUE TITLE
SI Article 5 PD to NC

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#175]
The hierarchical approach doesn't apply to a an agglomeration that is under pending deadline regarding article 5. It can not be "NC" because the deadline has  not expired.

We have this issue in Slovenia register with  

SI_PTUJ_15065
SI_ŠKOFJA LOKA_20570
SI_LOKA *_3806

![pdnc](https://cloud.githubusercontent.com/assets/16286544/13051340/ff6a53f2-d3f8-11e5-91a3-f07735eb495c.PNG)

It seems correct in the map viewer. This problem is certainly only in the register

**Comment by friboben** [comment]
in all cases when the agglomeration is PD for the article 5, the hierarchical compliance art5 should state PD, except if compliance art5a/b/c only state NR, in which case the hierarchical 5a/b/c should state NR. An for whole agglo at end (of blue part, see above), the hierarchical should also state PD when at least one of the previous hierarchical state PD.

**Comment by bbondier** [comment]
In all those case, the agglomeration is NC for either art 4 or art 3, so the hierarchical approach states "NC". Isn't that a normal behavior ?

**Comment by Rakedjian** [comment]
But it is not NC under Article 5 because deadlines are pending.

**Comment by friboben** [comment]
if deadline is pending, should be reported as PD

**Comment by bbondier** [comment]
Fixed
