### ISSUE TITLE
Nitrate and othophosphate layer

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#176]
Is it on purpose that we have to zoom to display the information. Nothing appears at European level for nitrates and orthophosphates. On the contrary we have all the dots with monitoring station layer.

**Comment by ndhuygelaere** [comment]
We are dependant of webservices settings for each layer. Providers can decide to fix some limit scale for display layer. But is it really a purpose for a national  framework to display this kind of layer at european scale ?

**Comment by Rakedjian** [comment]
It is ok but strange to have such difference. For bathing water we have a synthesis graph, for monitoring station all the points and here nothing. It could be interesting to have an overview at EU level to have a global picture of where the problems are.  

is the way the dot is displayed organised by the webservice or is it possible to have a triangle for Soes instead of the round to differentiate more clearly the dots.

**Comment by ndhuygelaere** [comment]
We have define new SoE layers provide EEA for NO3, NH3, PO4 & COD, and the new points are displayed with triangle.
=> can be viewed on devel website of lithuania

**Comment by Rakedjian** [comment]
Thanks

Don't spend a lot of time with this layers. If there are problems with the new layers please go back to the old version that worked well. 

I have this picture when I am at the first level with all parameters and then problem with zooming

![nh4 pb1](https://cloud.githubusercontent.com/assets/16286544/13434559/93fcf5d6-dfd6-11e5-9a9b-24ee10a65977.PNG)

![capture po4](https://cloud.githubusercontent.com/assets/16286544/13434693/17d248e8-dfd7-11e5-9536-e300a7be60fa.PNG)
