### ISSUE TITLE
distance to compliance treatment article 4

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#177]
We have some situations where the treatment is not in place and the distance to compliance is zero instead of the total load connected.

See the example of vesenik below

![distance to compliance article 4](https://cloud.githubusercontent.com/assets/16286544/13052032/d1311bde-d3fc-11e5-81c2-e9a9d9a02bed.PNG)

It seems to be ok in the compliance fiche of the agglomeration

http://webnuxdev.rnde.tm.fr/uwwtd_si/agglomeration/si09800/2012

**Comment by friboben** [comment]
This has to be checked for the columns distance art4 "treatment", where it seems not to be considered. The same rule as for the calculation of the fiche applies and the fiche is showing correct values.

**Comment by bbondier** [comment]
Fixed
