### ISSUE TITLE
REGISTER Lithuania starting date of application Sensitive area

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#185]
Don't remember if i sent already this remark that may be the same for all the registers.

In the register this is the starting data of application that has to be displayed and not the designation date. We have not this information under the old format but this information is available under the new format

![register sa starting date of application](https://cloud.githubusercontent.com/assets/16286544/13247153/2c9cf6c0-da18-11e5-8637-c36b360fb344.PNG)

**Comment by friboben** [comment]
In the case of Lithuania, we have this information in the field "rcaDateArt58" which is used here. For the others, as they are not provided in old dataset the result in register is -

**Comment by Rakedjian** [comment]
This is not the starting date; The starting date is in the accession treaty either 31/12/2007, or 31/12/2009. That's what is written in the Article 5 deadline.

**Comment by friboben** [comment]
Which date should we consider then, 2007 or 2009? In the data dictionary for last reporting the field was stated "Starting date of application of Art. 5(8)", if the xml is reporting an other date (which means data are wrong), we need to correct this in the database, as was the case for Slovenia. In such case it would be much better if the original file would be corrected by the country instead.

**Comment by Rakedjian** [comment]
In the LT register you have some agglomerations with deadline in 2007 and other with deadlines in 2009. It is related to the accession treaty and it has to remain. Agglomerations of more than 10 000 p.e. are under 2007 deadline and for agglomerations under 2009 there is no deadline concerning Article 5. 

http://ec.europa.eu/environment/water/water-urbanwaste/legislation/pdf/transitional_periods_eu10_eu2.pdf

That's the issue with the old template. UBA was obliged to adapt the deadlines to each of the countries that have specific date on the accession treaty.

What we have included in the new template is the starting date of application that is the date to take into account for Article 5 in the new reporting. The designation date is most of the time not the starting date of Application for Article 5.1 and 5.8..

**Comment by friboben** [comment]
deadlines to import before recalculating the compliance are in the herewith file
[LT_deadlines.xlsx](https://github.com/OIEau/uwwtd/files/143041/LT_deadlines.xlsx)
