### ISSUE TITLE
REGISTER LT TAURANGE distance to compliance 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#186]
Taurage is compliant Article 4 and in the fiche the distance to compliance is zero. In the register it is not zero. It has to be zero in the register too.

![register taurage distance to compliance](https://cloud.githubusercontent.com/assets/16286544/13249052/3538dae2-da22-11e5-9a1b-2b85fd86fd3f.PNG)

**Comment by friboben** [comment]
The problem was identified and the calculation is in course of correction.

**Comment by bbondier** [comment]
Fixed.
