### ISSUE TITLE
REGISTER LT and UWWTP-AGGLO compliance Kedainiai

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#187]
http://webnuxdev.rnde.tm.fr/uwwtd_lt/agglomeration/lt-ag-012/2011

http://webnuxdev.rnde.tm.fr/uwwtd_lt/treatment-plant/lt-ag-012-wwtp-01/2011

I don't understand why this agglomeration is considered as compliant as regards  the performance. The treatment required is 3 other and the performance fail. 

![register lithuania kedainiai](https://cloud.githubusercontent.com/assets/16286544/13249330/f6d15412-da23-11e5-89a6-cf8522b97b1e.PNG)

**Comment by friboben** [comment]
I ask for confirmation by UBA but the fact is that there is a mistake in algorithm 1 as for Art58 there is an other parameter to use to define the required treatment for a treatment plant (rcaParameterN & P). A new issue was created for this, the algorithm will be implemented and the calculation launched again, the result should state for this agglomeration required = 3NP and as there is no N treatment, it will be NC.

**Comment by Rakedjian** [comment]
I hope that all MS have N and P request under article 5.8. If not it will create new not compliant situations

**Comment by bbondier** [comment]
Fixed. New algorithm gives us a treatment required "More stringent treatment : Nitrogen and Phosphorus", this station is compliant as regard of performance, but doesn't have Nitrogen equipment in place.
