### ISSUE TITLE
REGISTER LT summary legal compliance article 5

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#190]
There is still an issue if we compare the old register to the new. In fact all the deadlines have expired. It is not possible to have a compliance table with so few agglomerations in the new register. 

This is the old register result

![regsiter lt article 5 summary legal compliance old](https://cloud.githubusercontent.com/assets/16286544/13259811/58d2a9f6-da59-11e5-8e6e-b163f3eb484a.PNG)

and the new one

![register lt article 5 summary legal compliance new](https://cloud.githubusercontent.com/assets/16286544/13259826/67d6c540-da59-11e5-9084-4f300e8ca8e9.PNG)

**Comment by friboben** [comment]
This is related to the algorithm, should be corrected once the new algo is implemented (not possible before Friday).

**Comment by bbondier** [comment]
Fixed.
