### ISSUE TITLE
Download invoke LT menu

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#191]
There is a problem when I try to open the XML or the CSV related to Agglomerations of the other objects

http://webnuxdev.rnde.tm.fr/uwwtd_lt/download

I have always this answer

_This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <ows:ExceptionReport version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://uwwtd.oieau.fr/services/schemas/ows/1.0.0/owsExceptionReport.xsd"><ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">ows:ExceptionTextFeature type UWWTD:UWWTD_recette_Lithuania_Agglomeration unknown/ows:ExceptionText/ows:Exception/ows:ExceptionReport_

The when I open the metadata I have not what is normally displayed but this message.

![metada](https://cloud.githubusercontent.com/assets/16286544/13260180/abb4a9c0-da5a-11e5-9f9f-555284702a2f.PNG)

The hyperlinks to this webpage don't work

**Comment by ndhuygelaere** [comment]
This error was due to miss-settings on geoserver.

**Comment by Rakedjian** [comment]
Has it been corrected ?

**Comment by friboben** [comment]
Yes on production platform.

**Comment by ndhuygelaere** [comment]
We issue was solved for dataservices but it appears that all metadata links are false.
The matter is not in the SIIF plateform but it is in the catalog => i try to fix this issue
