### ISSUE TITLE
Lithuania connection secondary treatment compliance graph

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#194]
This problem is certainly related to the problems found in the register

It is not possible to have less agglomerations under connection compliance than under Article 4 compliance. 

http://uwwtd.oieau.fr/lithuania/stats/graphs

![connection secondary treatment graphs](https://cloud.githubusercontent.com/assets/16286544/13290148/e7a6ea0c-db12-11e5-80fb-d15f70209d4c.PNG)

**Comment by friboben** [comment]
Agreed, in current register in table distance to compliance the sum of meet requirements for the lines under target connection is = 100% and value is 2757900
To be corrected.

**Comment by ndhuygelaere** [comment]
We use result of register calculation in order to create "distance to compliance" chart so, if we have a bug in the register, we also have a bug these charts.
An other stange thing in charts : we only have "compliant" serie but the legend display 3 series.

**Comment by Rakedjian** [comment]
Normally the statistics in the statistic webpage are about legal compliance and not distance to compliance, isn't it? Distance to compliance are only in the register.

**Comment by ndhuygelaere** [comment]
We display legal compliance, but the block title is "Distance to compliance" => it's the good title or not ?

**Comment by friboben** [comment]
No, has to be changed to "Legal compliance"

**Comment by ndhuygelaere** [comment]
So, i change the title and i check data, charts are corresponding with provided data. So we just "have" to fix issue in the register calculation for have true charts and true register.

**Comment by Rakedjian** [comment]
It has to be legal compliance here and not distance to compliance that will only be in the register for this version of the website.

**Comment by ndhuygelaere** [comment]
fixed
We are going to reprocess data in order to produce the new register for lithuania on the devel website
