### ISSUE TITLE
REGISTER IRELAND summary legal compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#195]
There is only two less sensitive areas in Europe in Portugal.

It is a wrong affectation of the number in the Article 5 legal compliance table that has to be in the normal area line

New register
![ie article 5 compliance](https://cloud.githubusercontent.com/assets/16286544/13291524/610cff44-db18-11e5-888b-f2ed8e303b6b.PNG)

Old register

![ie article 5 compliance old](https://cloud.githubusercontent.com/assets/16286544/13291530/6585adb4-db18-11e5-9e74-c1d687b8a8a1.PNG)

**Comment by friboben** [comment]
partly fixed but:
1. line "target" has only to consider expired deadline (same for art4/target)
2. line 0% collection should only consider the case when 0% is collected in collecting system + <2% &<2000pe in "neither collecting system nor IAS" 
3. line "- size > 10000 p.e. and discharge into …..SA/CSA, but transition period pending" should include all agglomerations >10000 with "type of receiving area" all except LSA and NA
