### ISSUE TITLE
kildare town Ireland distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#196]
I hope that this problem will be solved with the new version

http://webnuxdev.rnde.tm.fr/uwwtd/agglomeration/ieag_202/2012

In this situation this is a little complicated because in fact the second treatment is in place and it si Ok in the wevbsite how the distance to compliance is calculated but in the register the treatment is considered as not compliant

Concerning the more stringent treatment, the treatment is not in place but the performance are not met because the BOD and COD fail. It means that the distance to compliance performance for more stringent treatment is not zero. The register has also to be corrected concerning the article 5 performance.

![kildare town](https://cloud.githubusercontent.com/assets/16286544/13292529/6e1f2c12-db1c-11e5-92c4-316b8587caee.PNG)

![kildare distance to compliance](https://cloud.githubusercontent.com/assets/16286544/13292531/72058f06-db1c-11e5-9817-144599bfe009.PNG)

**Comment by friboben** [comment]
Two problems:
A) website, table distance, column performance has to consider BOD, COD, N and P and only when all =pass is compliant
B) Register
* columns distance to compliance article 4 treatment have to be corrected, here kildare is equiped in 2, thus columns treatment should be = 0
* columns distance to compliance article 5 performance have to be corrected, to consider not only the N and P but also BOD and COD
* columns monitoring results f. more string. OK has to consider not only the N and P but also BOD and COD

**Comment by bbondier** [comment]
Fixed.
