### ISSUE TITLE
Lithuania Compliance Article 5

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#200]
Don't know if it is the last version of the website and the algorithms updated but there is a problem with the legal compliance article 5 graph. All the agglomerations of more than 10000 have expired deadlines. It is not possible to have not relevant situation. 

![article5lithuania](https://cloud.githubusercontent.com/assets/16286544/13462359/4a79c108-e087-11e5-9bc1-b0e229a5e361.PNG)

**Comment by friboben** [comment]
It stems from register calculation: like for compliance calculation, A58 case is not correctly adressed in current version: we have found part of the problems but could not finish today. There are 34 agglomeration out of the 67 agglomeration in total for LT that are relevant for article 5 of which 2 are NC and 32 are C, and 33 should be not relevant (<10000pe).

**Comment by bbondier** [comment]
Fixed
