### ISSUE TITLE
fullscreen map

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#202]
Some times when i click on the button to have thefullscreen map, I have this result; The map disappears

![zoom map](https://cloud.githubusercontent.com/assets/16286544/13597907/4b4eb492-e51b-11e5-8e10-997d2b45a6f3.PNG)

**Comment by ndhuygelaere** [comment]
can you give us more details on this bug : pages (url), actiavted layers, frenquency (eg:every morning), used browsers (eg:ie 11, firefox, chrome...) , message provide by the browser when the bug occurs.

**Comment by Rakedjian** [comment]
It is when I zoom in first and then I click on the full screen button
