### ISSUE TITLE
white map lithuania pressure

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#203]
I have a write map when I want to open the lithuanian pressure map

![lithuania pressure](https://cloud.githubusercontent.com/assets/16286544/13673333/db7c579a-e6d8-11e5-81f2-ba22af4acad3.PNG)

**Comment by ndhuygelaere** [comment]
It more probably the result of an error on the production website. This map works well on the devel website ==> we need to update all production website with the last change.
