### ISSUE TITLE
Prefilled DB dump file for Cyprus

### ISSUE THREAD

**Issue by chadjistyllis** [OIEau/uwwtd#207]
Cannot find prefilled DB dump files in repository. Looking for Cyprus' specifically, but cannot find them in general. This step is suggested in section 2.2 of UWWTD-SIIF-Toolbox-2015-installation-guide-vf.pdf.

**Comment by friboben** [comment]
Dear Christos, we do not disclose the individual dumps here, the Github platform being publically available, and as they are for country UWWTD SIIF platform administrator only, but we can prepare this for you and send a private link. Yours.

**Comment by chadjistyllis** [comment]
OK that would be perfect.
