### ISSUE TITLE
fullscreen of the map

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#211]
When i use the fullscreen button in the agglomeration compliant map there is a problem with the legend and the scrolling button that doesn't wor
http://uwwtd.oieau.fr/agglomerations/compliance

**Comment by cnassar** [comment]
@Rakedjian can you check again please ? The problem seems to be solved. However, I prefer to be sure that it is not linked to the browser.

**Comment by Rakedjian** [comment]
Seems to be Ok now
