### ISSUE TITLE
graphical network summary

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#212]
Currently when load entering treatment plant is >1% or >=2000p.e. 2nd treatment compliance is NC (not compliant) see here http://webnuxdev.rnde.tm.fr/uwwtd_de/agglomeration/deagth9443/2012 but the graphical network summary shows the network and the treatment plant compliant: the treatment plant should be NC (red) and for the treatment plant fiche the graphical network summary shows the treatment plant compliant and the network not compliant, example here http://webnuxdev.rnde.tm.fr/uwwtd_de/treatment-plant/detpth9443/2012: it should be the reverse: treatment plant red (NC) and network green.
For both Treatment fiche and agglo fiche: network is red only when collection is NC.
You have to add a case when the 1% and 2000 pe criteria is not met with the line linking network and plant in red.
In addition, when the treatment required is more stringent and the treatment in place is more stringent, the main treatment is compliant if both the above criteria is valid and if treatment in place = secondary treament + performance BOD5 and COD=pass.
Normally here http://webnuxdev.rnde.tm.fr/uwwtd_dk/treatment-plant/dk6551002/2014 the network should be green, the main treatment should be red (1st criteria 1% not valid, but treatment in place = secondary treament + performance BOD5 and COD=pass) and N and P should be red (performance = NR).

**Comment by bbondier** [comment]
Partially fixed, further discussion required

**Comment by friboben** [comment]
In this case http://webnuxdev.rnde.tm.fr/uwwtd_ro/agglomeration/roag_106755/2014 the load entering from should be green (sum = collective) and distance to compliance table what is blue should be =0 (rounding, include a rule to have negative values rounded to = 0.
