### ISSUE TITLE
distance to compliance table for agglomeration fiche

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#213]
when (load collected - load entering a treatment plant) >1% or >=2000p.e. , the 2nd treatment is considered not compliant. Currently this is reported in agglomeration fiche but in the table distance to compliance, the loads for both columns treatment and performance are =0 if the treatment plant performance and equipement are OK. This is correct but incomplete. This should be corrected with following calculation: when (load collected - load entering a treatment plant)>1% or >=2000p.e., both columns should have (load collected - load entering a treatment plant). When above 1% OR 2000pe (lowest of both criteria) the colour becomes red for both the % and the pe, when below it stays blue.
 - (all what is above 1% or >=2000p.e.). This should be added to the current formula.
For instance for this case: http://webnuxdev.rnde.tm.fr/uwwtd_de/agglomeration/deagth52602/2012
(load collected 2044pe - load entering a treatment plant 1515pe)=529p.e. as 1% of load collected =20p.e. the criteria is valid, hence the distance to compliance table should report 529pe.
for this case http://webnuxdev.rnde.tm.fr/uwwtd_de/agglomeration/deagth8644/2012 the difference is 2661pe, hence the distance to compliance table should report 2661pe which corresponds to 0,18% ie below 1% but above 2000pe. hence both lines red.

An additionnal problem occurs when more than 1 treatment plant like here http://webnuxdev.rnde.tm.fr/uwwtd_dk/agglomeration/dk436/2014 the calculation seems to consider only one treatment plant and hence enter in non compliance due to load entering treatment plant: correct calculation to consider also this case because in this case 2nd treatment should be compliant and 3rd treatment should be compliant and blue (not red). In case http://webnuxdev.rnde.tm.fr/uwwtd_dk/agglomeration/dk436/2012 the distance to compliance should be blue for all: performance for 3rd is met for both treatment plants.

**Comment by bbondier** [comment]
Fixed in germany.

Still working on DK
