### ISSUE TITLE
specific case for algo 1 (54523 and 5854523)

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#216]
for these specific case under 9th reporting, implement the specific rule that required = ? (see file)
[UWWTD_SIIF_Phase III_ Task_I.1_compliance-algorithms-draft17.docx](https://github.com/OIEau/uwwtd/files/454581/UWWTD_SIIF_Phase.III_.Task_I.1_compliance-algorithms-draft17.docx)

**Comment by bbondier** [comment]
Done
