### ISSUE TITLE
sensitive area fiche

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#217]
reorganise to reflect the herewith file as far as possible
[sensitiveareafiche-annotated.xlsx](https://github.com/OIEau/uwwtd/files/454589/sensitiveareafiche-annotated.xlsx)

**Comment by friboben** [comment]
There is also the box description2014 where the calculations are all at 0: check fields and calculations and correction.

**Comment by vincentgode** [comment]
Fixed

**Comment by friboben** [comment]
It is a bit difficult to link each line with the dates, should be improved with underlying colours like here http://webnuxdev.rnde.tm.fr/uwwtd_at/agglomerations/compliance
