### ISSUE TITLE
discharge without treatment

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#218]
When an agglomeration has value for discharge without treatment above 0, a 2% and 2000pe criteria is applied (see algorithms). In such case, it should be reflected in table distance to compliance for secondary and tertiary (if relevant). the values in columns equipment and performance should be filled for lines secondary (and tertiary), and put in red when above the criteria and stay the current colour if below. For instance here http://webnuxdev.rnde.tm.fr/uwwtd_ee/agglomeration/eerka0370072/2014 treatment plant requires secondary, and table distance to compliance should show in red on lines secondary for equipment and performance the 42%. (Nota: if required would have been tertiary, then would have implied also to see this 42% in line 3rd treatment, if not 42% but 1,9% same but colour in blue).
Nota: In the above example there is also a problem in table distance because 2nd treatment should have been blue (currently TP is compliant) and not grey.

**Comment by bbondier** [comment]
Fixed

**Comment by friboben** [comment]
Has to be corrected: the 42% are only to be considered for article 3. For art4 and 5 it has not to be considered as we can not decide if the country will chose collective or IAS.
