### ISSUE TITLE
Romanian agglomeration compliance mapviewer

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#225]
When I click on the agglomeration compliance mapviewer I have 2012 reference year and no possibility to display 2014 but when I start to sort the information I have 2014

![romania agglomeration](https://cloud.githubusercontent.com/assets/16286544/18514849/6aad45e8-7a93-11e6-9cf8-2acd1db0dca2.GIF)

The connection map is not working (blank in the mapviewer

**Comment by friboben** [comment]
It is the latest dataset imported this morning, we are checking, but by us it works well: maybe close your browser and reopen.

**Comment by Rakedjian** [comment]
I have the same problem this morning and with explorer and firefox

**Comment by friboben** [comment]
This was due to an IT issue: new import should be followed by an "empty the cache" process to avoid this. Should work now.
