### ISSUE TITLE
Demark Agglomeration of HUMMINGEN

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#226]
This agglomeration does not appear in the home and agglomeration mapviewers but it is located in the agglomeration fiche

There is a mistake with only a primary treatment declared that explains the not compliance in equipment but the distance to compliance as regards secondary treatment is zero.
In the picture the agglomeration is in green 
There is also a problem of load entering certainly a mistake in the database
Agglomeration fiche
http://webnuxdev.rnde.tm.fr/uwwtd_dk/agglomeration/dk611/2014
Treatment plant fiche
http://webnuxdev.rnde.tm.fr/uwwtd_dk/treatment-plant/dk3810012/2014

**Comment by friboben** [comment]
solved
