### ISSUE TITLE
Suppression of decimals in the SA article calculation

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#227]
It could be better to suppress the decimals in the Article 5.4 calculation in order to have the information more readable. 

http://webnuxdev.rnde.tm.fr/uwwtd_dk/receiving-area/dk1/2014

![sa sensitive area calculation amount format](https://cloud.githubusercontent.com/assets/16286544/18746134/ff22fd2a-80c5-11e6-8442-df635f2db290.GIF)

**Comment by friboben** [comment]
maybe we keep the 2 digits after comma for % and put integer only for tons/year?

**Comment by Rakedjian** [comment]
1 digit is sufficient for %

**Comment by Rakedjian** [comment]
Is it also possible to align the numbers?
