### ISSUE TITLE
Blue color instead of red color for distance to compliance (3rd treatment)

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#228]
http://webnuxdev.rnde.tm.fr/uwwtd_bg/agglomeration/bgag6885000/2012

**Comment by friboben** [comment]
And blue in timeline instead of dark grey (missing information) for 2014. Would be good also to have all cells of table distance to compliance where compliance is unknown ie '?' in dark grey if not too complicated to implement.
