### ISSUE TITLE
Possibilité d'utiliser le site pour trouver des coordonnées X,Y sur une carte

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#23]
J'avais déjà formulé cette requite il y a quelques temps c'est la possibilité d'afficher le X,Y en bas de la carte lorsque l'on promène le pointeur sur la carte. Cette function est très utile pour trouver des X,Y manquant

**Comment by ndhuygelaere** [comment]
fonction ajoutée
