### ISSUE TITLE
Entering load equal to zero, but this entering load is provided by the XML file

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#230]
http://webnuxdev.rnde.tm.fr/uwwtd_cz/agglomeration/czag597783/2014

**Comment by friboben** [comment]
This is not a mistake of the tool, the node uwwtagglo set percentering=0, country to correct.

**Comment by Rakedjian** [comment]
It is strange because if it is really zero the load connected entering the treatment plant it means that there is a direct discharge during collection. It means really Article 4 not compliant.
