### ISSUE TITLE
SA active or inactive

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#236]
Pb of active and inactive SA in Denmark due certainly to bad connection of the parameters to the algorithms.
In the XML it is written the following for dk SA. It means that this SA is inactive because the end of life is 2014-12-31. 

http://webnuxdev.rnde.tm.fr/uwwtd_dk/receiving-area/dk/2014

On the contrary the other sensitive areas have only a beginlife and no endlife and they are declared inactive 

http://webnuxdev.rnde.tm.fr/uwwtd_dk/receiving-area/dk3/2014

This is normal that dk is no more connected to UWWTPs because it is closed

XML of dk

dd843:repCodeDK2015/dd843:repCodedd843:rcaCodeDK/dd843:rcaCodedd843:rcaNameDenmark/dd843:rcaNamedd843:rcaEnvDomWATER/dd843:rcaEnvDomdd843:rcaZtypeUWWCMSA/dd843:rcaZtypedd843:rcaSpZTypA58523/dd843:rcaSpZTypdd843:rcaParameterNtrue/dd843:rcaParameterNdd843:rcaParameterPtrue/dd843:rcaParameterPdd843:rcaParameterMfalse/dd843:rcaParameterMdd843:rcaParameterOtherfalse/dd843:rcaParameterOtherdd843:rcaArt58DateDesign1993-12-31/dd843:rcaArt58DateDesigndd843:rcaDateArt581998-12-13/dd843:rcaDateArt58dd843:rcaRemarksSome of the more stringent demands: National stadards on 8 mg/l of nitrogen in the outlet for treatement plants above 5000 PE. WWTP above 2000 PE must meet COD 75 mg/l and 15 mg/l of BOD./dd843:rcaRemarksdd843:rcaHyperlinkhttp://svana.dk/vand/vandomraadeplaner/vandomraadeplaner-2015-2021/vandomraadeplaner-2015-2021//dd843:rcaHyperlinkdd843:rcaBeginLife1998-12-31/dd843:rcaBeginLifedd843:rcaEndLife2014-12-31/dd843:rcaEndLife

Proposal of new organisation of the fiche following

**Comment by friboben** [comment]
a) I do not agree: we are evaluating data reported on 31/12/2014 for year 2014. The whole country SA is closed as at 1/01/2015, hence active for 2014. If it is not active for 2014 end life should be 31/12/2013 or earlier. Maybe a mistake by the country?
b) This is true, no end life means the SA is active, should be corrected.

**Comment by Rakedjian** [comment]
You are right and they have connected the discharge points to the DK1 to 4 and not DK. It means that for the current reporting this are the DK1 to 4 that are active.
