### ISSUE TITLE
SA new presentation for the charasterics

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#238]
Please find attached a proposal to better organise the content of the characterisation of the SA. It seems that there are lots of problem of connection between the parameters and the XML. 

[SA characteristic.xlsx](https://github.com/OIEau/uwwtd/files/503022/SA.characteristic.xlsx)

Don't understand why you have 
"75% removal Nitrogen and Phosphorus" and "article 5(4) applied" because this is the same parameter. It is strange not to find the same information. 
The original idea was to simplify the access to this information for a non expert.

**Comment by friboben** [comment]
These issues are related to the large change of SA information between 8 and 9th. Information to use are found in different fields in 8 and 9th. Has to be solved when Benjamin is back as he developed the import tool and is the most suited to do this (24-10).
