### ISSUE TITLE
Registre- Zones sensibles - criteria b

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#24]
Merci de compléter les paramètres de date pour les critères b et c en précisant b et c dans les critères de designation and starting date of application.

D'autre part dans le cas de l'Irlande est ce normal d'avoir une date dans la case starting date of application

![registrezscriteria b et c](https://cloud.githubusercontent.com/assets/16286544/11777117/693d806c-a24c-11e5-9a33-0f423c124fe2.PNG)

**Comment by friboben** [comment]
Starting date of application can not be filled in with the xml file. When 1 in column designation criteria it means it applies and when 0 it means it does not apply.
Correction needed on column M, P and S to work like column V where no date when criteria do not apply (=0)

**Comment by bbondier** [comment]
Fixed
