### ISSUE TITLE
Historical statistics in Lithunia

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#240]
It is not only in Lithunia but also in some other member States and certainly because work is ongoing.

When we select all years there is only one graph available and for the other fields only the tables without the graphs. 
http://webnuxdev.rnde.tm.fr/uwwtd_lt/stats/graphs

 I suppose that these websites have not been updated yet with the last version of the website  but when we are going to start exchanging with Member states it is important to have this webpage finished

**Comment by friboben** [comment]
Flush cache does not solve, bug to be corrected, problem not found in DK for instance.
