### ISSUE TITLE
Agglomeration with ?

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#242]
When i select these agglomerations all the deadlines have expired and it seems that there is direct discharge without treatment.
Why is declared no information (because of lack of connection to a virtual treatment plant fiche ?)
http://webnuxdev.rnde.tm.fr/uwwtd_bg/agglomeration/bgag7278900/2014
Don't know also why secondary treatment is not relevant. It is certainly unknown not not relevant and due to lack of connection to the object UWWTP.
Does it mean that for all these agglomerations there is a need for Bulgaria to complete the database?
It is strange because this database seems to be considered as compliant related to the use in the SIIF

**Comment by friboben** [comment]
a) This is not my interpretation: I had a look at 2 agglomerations in this case and deadline is set at 31/12/2014. For data reported for the year 2014, the deadline is not passed.
b) Each time there is a ?, it mean there is missing information which prevent from calculating automatically the compliance, hence results should not be considered relevant or reliable. In the case of Rozino for instance, no link to discharge point is provided, while it is necessary to create a discharge point and link this to the table uwwtagglo when no treatment plant. BG has to complete the database.

**Comment by Rakedjian** [comment]
Sorry but 31/12/2014 deadline has expired because the reference year is 2014. And reference year 2014 means analyse of the situation of the agglomeration at the end of 2014 using all the data of 2014 to calculate the performance.
