### ISSUE TITLE
REGISTER AGGLO Sheet more stringent treatment deadline

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#244]
The more stringent deadline has to be related to the starting date of the Sensitive area linked to the discharge point of the treatment plant. This is not the case here. In Denmark the deadline is 31/12/1998 and not 31/12/2005.

This is the same in the UWWTP level for the agglomeration information.

**Comment by Rakedjian** [comment]
I sent also to DK a message to change the deadline in the agglo reporting table  but in countries like france when we have deadline concerning Article 3 and 4 in the agglo table and a discharge in sensitive area, most of the time, it is not the same deadline. That's why it is important to use the starting date of the SA in the calculation of he Article 5 deadline. This is the real one When there are different starting dates one for phosphorus and one for nitrogen (only in France I presume) please use the first one to simplify.

We reach here the limit of the data model. The best way to manage that better in the future is normally to allocate a deadline to article 3 and 4 and another deadline to article 5 in the agglo table. If we do that there will be no need to create an algorithme to import this information from SA.

**Comment by friboben** [comment]
Actually for 9th reporting aggforecast is said to be deadline for article 3 as far as I understand the data dictionary and agg period over to state article 4 and 5 deadline, and also 3 when aggforecast is not provided. Is it correct?
Else taking the "Starting date of application: " from SA for art5 will be very complicated as their are different fields for that depending on sub-article that apply (54, 523, 58...).
For DK we used the field "aggperiodover" to populate article3-4-5 deadlines as the field . But isn't it 1998 which should apply? not clear why the country provides a different date?

**Comment by Rakedjian** [comment]
We have to find a solution with France because there are really pending deadlines only concerning Article 5. It is a few number of agglomeration and I am not sure that lots are not compliant. 
For the expected deadline it is not a problem for the calculation but for these specific cases it might be  a problem. Of course the date that is in the fiche is not the correct one concerning Article 5.
Don't know if there is a need to change the algorithm or to identify specifically the list of agglomeration to change manually in the database of the website the information. It is certainly the best way to process this issue. 
I am going to propose an evolution of the datamodel in 2017 to solve this problem and not to have to refer to Sensitive area for each agglomeration deadline. 
What is important with France is to be sure that article 5.4 is taken into account

**Comment by cnassar** [comment]
For this reporting, the problem has to be solved manualy.
For the next reporting, new filds have to be added in the XML, for eache article ( artiles 3, 4 and 5).
For the moment, only one field provides a dedaline (aggperiodover). It is usually used for article 3 deadline.
