### ISSUE TITLE
registre zone sensible 54 incoming et discharged load

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#25]
Lorsque l'Article 54 ne s'applique pas on ne devrait pas avoir d'information dans les cases

![registrezsarticle54 incoming et discharges load](https://cloud.githubusercontent.com/assets/16286544/11777206/0ec4d378-a24d-11e5-9552-59c373d28353.PNG)

**Comment by friboben** [comment]
if column AA = null then column AC, AE AF and AH = null

**Comment by bbondier** [comment]
Fixed
