### ISSUE TITLE
DK register summary big city

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#250]
The summary big city sheet is empty in the register

**Comment by friboben** [comment]
This is an issue related to the data collection: the node on big cities has completely disappeared from the xml in all countries, not only for DK. Was it instruction from COM?

**Comment by Rakedjian** [comment]
If it is related to that, the solution is to select all agglomerations of more than 150 000 p.e. directly from the reporting database. No need to ask for this information

**Comment by bbondier** [comment]
Fixed
