### ISSUE TITLE
Graph adjustment in statistic webpage

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#252]
We don't see the whole number of the graphs attached to the vertical axis in the statistic webpage

http://webnuxdev.rnde.tm.fr/uwwtd_nl/stats/graphs

![graph adjustment](https://cloud.githubusercontent.com/assets/16286544/19104806/d4d2aef8-8ade-11e6-82df-460e374e0db8.GIF)

As regards the legend of this specific graph it is not only "< 10 000 p.e." but "2000 to 10 000 p.e." and then <10 000 to 100 000 p.e.

It is important to put the threshold at 2000 p.e. because if we don't do that and we reuse the graph some people can imagine that small agglomerations below 2000 p.e. are included

**Comment by friboben** [comment]
Small adjustment to visualisation. See also here similar adjustment needed: http://webnuxdev.rnde.tm.fr/uwwtd_lt/stats/graphs
