### ISSUE TITLE
AGGLOMERATION sheet deadline column

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#254]
It is certainly a detail that has no influence but i have remarked that when the discharge is in coastal area there is no information in the cell about the EXPIRED deadline. Normally the deadline is the same even if the compliance is not calculated in the same way.

This is picture of the NL register

![register expire deadline](https://cloud.githubusercontent.com/assets/16286544/19109362/58f5b534-8af5-11e6-8955-cf766e754d95.GIF)

**Comment by friboben** [comment]
To be corrected. Use same formula as for freshwater, ie check deadline art3, 4 and 5 and if all expired put EXP, if none expired PD, if partially EXP-PD.

**Comment by bbondier** [comment]
Fixed
