### ISSUE TITLE
DK Installation in place sheet

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#255]
In the register I wonder why as regards the installation in place more stringent treatment, monitoring results meet requirement for discharges for all agglomeration. there was no information provided about the real performance considering that Article 5.4 is operational but the reality is that we don't really no the real individual performance. This information has not been reported. 
I thought that in this case the result was not to take into account this information as it was in DK.

![register installation in place nl](https://cloud.githubusercontent.com/assets/16286544/19112816/2ed1b50c-8b07-11e6-992f-4c3148f062a2.GIF)

In the legend of the table it is written "monitoring results meet requirements for discharge… corresponding monitoring results were reported with 'pass'". In NL it was never reported pass but NR

**Comment by friboben** [comment]
Question:
individual performance is not mandatory to be reported: do we only count when it is reported at pass for N and P?
Corrections needed:
- Title of table to be corrected to refer to correct article (for NL it is 5854)
- if answer to above is yes, correct calculation (result will be 0 for NL for more stringent)

**Comment by Rakedjian** [comment]
Not sure that there is a need to change the title.

This table is dedicated to the real situation of the treatment in performance in place. Whithout performance information we are not able to conclude that the performance are met at individual level. If a MS wants this information to be included in the reporting he has to include pass or fail. We will have zero as regards the **performance** for NL if they don't fill N and P with pass or fail.

**Comment by bbondier** [comment]
Done
