### ISSUE TITLE
LUXEMBOURG agglomeration pb of display of not compliant treatment plant 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#256]
It seems than for Luxembourg agglomeration there is a pb in the picture that does not show the not compliance of Bonnevoie UWWTP

http://webnuxdev.rnde.tm.fr/uwwtd_lu/agglomeration/luaggl101/2014

N treatment is missing but it does not appear in the picture in red

http://webnuxdev.rnde.tm.fr/uwwtd_lu/treatment-plant/lustep1b002/2014

**Comment by friboben** [comment]
graph is showing treatment in place, in this case it is not in place, hence the plant is not compliant for P but it is not visible on the graph.
An enhancement could be to have like when no secondary treatment while required, a picture for P with small dots in red to represent the fact it should be here but is not. Proposal: add to list of enhancements.

**Comment by Rakedjian** [comment]
What is strange is to have a green situation in the picture for a treatment plant that is not compliant. There are other situation where we have a red square situation for N. Does it mean that the red is only displayed when it is related to the performance?
If it is the case,as proposed by you, it has to be added in the proposal of improvement. The list of potential improvement is becoming to be important.

**Comment by friboben** [comment]
Yes, for more stringent, it works like that for all cases: if performance is fail, but equipment is in place the square is red, if no equipment, the square is not created, and similar if no equipment but performance is pass, the square is not created. OK I add it to list of improvements.
