### ISSUE TITLE
Problem of calculation in the table "distance to the compliance" of the register (Lithuania)

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#258]
![image](https://cloud.githubusercontent.com/assets/22166796/19154621/945e89fc-8bdb-11e6-9055-5c0f4b6f0be2.png)
The distance to the compliance cannot be 0% because there is one agglomeration that is not compliant.

**Comment by friboben** [comment]
Is not 0 but -0,1%, and should be 0,1% instead, but the issue probably comes from the formula and value in next column which is also negative.

**Comment by cnassar** [comment]
In fact the -0.1% is another problem, linked to the php structure, but we said the we correct this manually (it is due to the 100.1%). The problem is that the distance to compliance must be 1.6% (100% - 98.4% "compliance rate article 5") because there is only on non-compliant WWTP.

**Comment by bbondier** [comment]
Error linked to dataset, seen with @cnassar

Closing the issue, as it is not code related.
