### ISSUE TITLE
Problem in the attribution of the different articles of the Directive for sensitive area

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#259]
http://webnuxdev.rnde.tm.fr/uwwtd_lt/receiving-area/lt/2014

![image](https://cloud.githubusercontent.com/assets/22166796/19154895/9506652c-8bdc-11e6-9f47-cc3715caa44f.png)
Lithuania applies Article 5(8) and article 5(2,3).

**Comment by cnassar** [comment]
I will try to re-import the XML file first to see if the problem still.

**Comment by cnassar** [comment]
The problem still here. There is the same problem with Luxembourg that I imported yesterday

**Comment by friboben** [comment]
Chady,

Ya un vrai pb d'affichage mais bruno a demandé une révision complète de 
l'affichage. Je crois qu'il y a aussi un pb (lié?) de calcul des algo 
qui considèrent pas les bons sous articles (54, 523...)

Il y a déjà plusieurs "issues" sur ce pb de l'affichage de la fiche SA, 
il vaudrait mieux ne pas en créer trop parce qu'après il faut les 
vérifier une par une et les fermer.

https://github.com/OIEau/uwwtd/issues/251

https://github.com/OIEau/uwwtd/issues/237

https://github.com/OIEau/uwwtd/issues/238

notamment.

Benoit.

***********************************************************************************
Benoît FRIBOURG-BLANC
OIE/IOW (Office International de l'Eau/International Office for Water)
15 rue Edouard Chamberland
87065 LIMOGES Cedex, France
Tel. 33.5.55.11.47.97 ou/or 47.80

Skype: fribourg.blanc
Fax 33.5.55.11.47.48
E.mail : b.fribourg-blanc@oieau.fr
web: http://www.oieau.org

***********************************************************************************
UWWTD SIIF national WEBSITES: IE: http://uwwtd.oieau.fr/ - CY: http://uwwtd.oieau.fr/cyprus/ -
LT: http://uwwtd.oieau.fr/lithuania/ - SI: http://uwwtd.oieau.fr/Slovenian/
HR: http://uwwtd.oieau.fr/croatia/ - PL: http://uwwtd.oieau.fr/poland/ - RO: http://uwwtd.oieau.fr/romania

Natural Water Retention Measures: http://www.nwrm.eu/

L'Office International de l'Eau se mobilise pour l'environnement - MERCI DE N'IMPRIMER CE COURRIEL QUE SI NECESSAIRE
International Office for Water is environmentally involved- THANK YOU FOR ONLY PRINTING THIS E-MAIL IF NECESSARY

**Comment by cnassar** [comment]
D'accord
