### ISSUE TITLE
Luxembourg statistics

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#261]
There is certainly a mistake of 1000 in the calculation of concentration in the statistic webpage concening BOD, COD, N and P

http://webnuxdev.rnde.tm.fr/uwwtd_lu/stats/graphs

![graph concentration](https://cloud.githubusercontent.com/assets/16286544/19314731/7f3d9db4-909b-11e6-86b9-b1fd52ede5d4.GIF)

**Comment by friboben** [comment]
True, mistakes in 
a) table load (rate) 
b) and table concentration (mg/l columns), 
c) miss table concentration for phosphorus, to be corrected.

**Comment by bbondier** [comment]
Fixed
