### ISSUE TITLE
LU distance to compliance summary table

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#262]
I am surprised not to fine an amount in the article 5 related to distance to compliance. There is an amount in the Article 5 of the agglomeration table and normally we have to find the result here and not zero

![luxembourg distance to compliance](https://cloud.githubusercontent.com/assets/16286544/19316441/bb763cf4-90a1-11e6-91fe-5f226001e283.GIF)

**Comment by Yasham** [comment]
Fixed.
@cnassar can you confirm?

**Comment by cnassar** [comment]
yes it is fixed
