### ISSUE TITLE
LU installation in place

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#263]
There is something in the calculation of installation in place in the agglomeration table and the result is found in the summary table.

We have several agglomerations that have zero as regards more stringent treatment installed but 100% as regards more stringent monitoring results.

If i have a look at the agglomeration of Junglinster that is in the list

http://webnuxdev.rnde.tm.fr/uwwtd_lu/treatment-plant/lustep125b005/2014

the treatment declared is secondary. It is ok here but there is no more stringent performance pass for this agglomeration. It is only written not relevant

![lu installation in place](https://cloud.githubusercontent.com/assets/16286544/19316717/cdf77964-90a2-11e6-9861-dee613b80831.GIF)

**Comment by friboben** [comment]
Obvious mistake in calculation of register for sheet "agglomeration level" columns "monitoring results f. more string. OK" as can also be seen in the case of Bridel where treatment is in place but performance not reported: http://webnuxdev.rnde.tm.fr/uwwtd_lu/treatment-plant/lustep208b001/2014
Has to be corrected.
