### ISSUE TITLE
SK UWWTPs  that does not appear in the home map

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#264]
There are agglomerations with very small UWWTPs that does not appear in the map

http://webnuxdev.rnde.tm.fr/uwwtd_sk/treatment-plant/skcao30603445137412/2014

http://webnuxdev.rnde.tm.fr/uwwtd_sk/treatment-plant/skcao30603445137411/2014

Normally if it belongs to agglomerations of 2000 p.e. and more it has be displayed.

Only agglomerations less than 2000 p.e. does not have to appear.

**Comment by friboben** [comment]
It effectively appears on the tool but as 2 TP have exactly same coordinates and size in the same category, it means two rounds on on the other and they are overlayed, the not compliant appearing on top: again a data provision issue.
