### ISSUE TITLE
Pb of location of UWWTPs in Slovakia

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#265]
I have seen lots of problems of location of UWWTPs in Slovakia. Is it a problem of bad coordinates  or format of coordinate?

This is an example
http://webnuxdev.rnde.tm.fr/uwwtd_sk/treatment-plant/skcao30800605136101/2014

In fact it is located near the discharge point that is in the other side of the river

http://webnuxdev.rnde.tm.fr/uwwtd_sk/discharge-point/skv2380dva/2014

If it is a problem of coordinates I will raise this issue with some examples

**Comment by friboben** [comment]
It is a problem coming from the provided dataset, to be sent back to MS, as can be seen on google map the TP is here (49,09-18,31 not 49,11-18,33 as reported in xml) see https://www.google.fr/maps/search/wastewater+treatment+service+%C3%A0+proximit%C3%A9+de+P%C3%BAchov,+Slovakia/@49.0948671,18.310117,226m/data=!3m1!1e3
