### ISSUE TITLE
Paris agglomeration compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#266]
Strange to see Paris not compliant as all the UWWTPS are compliant with the more stringent requirements. Don't understand why.

http://dev.oieau.fr/uwwtd_fr/agglomeration/fr030000175056/2014

Bruno

**Comment by friboben** [comment]
see also http://dev.oieau.fr/uwwtd_fr/agglomeration/fr030000175056/2012 real bug on distance to compliance.
