### ISSUE TITLE
Page d'accueil - couches qualité et pression

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#27]
Quid de l'intégration des couches qualité et pression sur la page d'accueil comme par exemple bathing water ou BOD concentration of river....

**Comment by ndhuygelaere** [comment]
L'integration de ces couches est en cours. Elles seront disponibles dès que possible via ce webservice : http://maps.oieau.fr/services/background?service=WMS&request=getCapabilities&version=1.1.3, puis ajouter sur les différenets carte du site

**Comment by bbondier** [comment]
Done.
