### ISSUE TITLE
IE register summary table Article 5 compliance transitional period

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#270]
It seems that in Ireland there are two agglomerations plants that have a transitional period concerning only article 5

Clonakilty and Environs
Ennis North

Why don't we find them in the summary compliance table concerning the article 5

![ie summary table transitional period article 5](https://cloud.githubusercontent.com/assets/16286544/19649514/60f0f404-9a06-11e6-93c0-ef608f79c33a.GIF)

**Comment by bbondier** [comment]
Fixed
