### ISSUE TITLE
IE register distance to compliance Article 5

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#271]
There is zero in the distance to compliance table concerning more stringent treatment pending deadline. If we consider that there are two agglomerations that are under pending deadlines concerning Article 5 it has to be included in this table.

![ie pending deadline distance to compliance](https://cloud.githubusercontent.com/assets/16286544/19649786/5d24eabe-9a07-11e6-9bb7-70fab9cb3d03.GIF)

**Comment by bbondier** [comment]
Partially fixed, need a review from @friboben when he returns.
