### ISSUE TITLE
AT register distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#272]
There is a problem in the distance to compliance summary table for Article 5 in austria
It can not be 100% as regards the performance related to more stringent treatment because all the agglomerations are compliant and it is what is declared in the UWWTp table and also in the website. 

It has to be zero for the distance to compliance  "monitoring result meet requirements for discharges

![distance to compliance austria](https://cloud.githubusercontent.com/assets/16286544/19685380/877228c6-9abc-11e6-94b5-6e81142340b2.GIF)

It is not the case concerning installation in place due to the fact that we have no performance information concerning more stringent treatment. The summary table installation in place is correct

**Comment by friboben** [comment]
I am not sure to understand the issue: there is no information on monitoring, hence 100% are in column distance. Do you want changes in 4 columns: figures in columns wastewater load and meet requirements (considering monitoring is compliant even if not reported) and 0% and 0 pe in the two columns distance or only changes in 2 columns distance to have 0% and 0pe? In this case we have to implement a specific formula to state the result should exclude all agglomerations on which 54 is applied.

**Comment by Rakedjian** [comment]
This is not installation in place approach but distance to official compliance. Article 5.4 applies in this country. The performance have to be considered as correct due to this article. The distance to compliance is zero for the performance due to Article 5.4.

**Comment by bbondier** [comment]
Fixed
