### ISSUE TITLE
AT register graph compliance load

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#273]
There is certainly an inversion in the graph concerning article 5 and taking into account the load. As regards the load that is in the table It is not normal to have the smallest part in blue.

![at compliance load graph](https://cloud.githubusercontent.com/assets/16286544/19685625/dab290b0-9abd-11e6-8d64-9e403dfbabc8.GIF)

**Comment by friboben** [comment]
No inversion but the scale shows 18,5Mio are compliant and 2Mio are NR. Scale is automatically adjusted by excel, will be corrected in report to show all pe.
Suprisingly the 8th report states 20.5Mio are compliant, while the smaller agglomerations do not have to comply with art5, and should be NR: is it normal? Beware, if yes to this question, this means there will be deviation between 8th and 9th report.

**Comment by Rakedjian** [comment]
The scale has really to start at zero because we have a first look at this type of graph we really don't see that it starts at 18 million
