### ISSUE TITLE
BG summary table register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#278]
I don't know if there is really an issue but when we sum the information from SA and NA table concerning Article 3 we don't obtain the same total than in the whole country table.

It fits with the target concerning Article 4 and 5 

![bg compliance summary table na and sa](https://cloud.githubusercontent.com/assets/16286544/19687689/c4e50f20-9ac6-11e6-9c24-462a0319eb59.GIF)

**Comment by friboben** [comment]
also different lines on exempted do not match: under checking/correction.

**Comment by friboben** [comment]
fixed by a filter on rca type.
