### ISSUE TITLE
Page de presentation du SIIF

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#28]
Il manqué les reference aux notes de bas de page et comme on a 1, 2 et 3, comme point dans le texte on peut penser que le 1,2,3 du bas fait reference à ces numéros ce qui n'est pas le cas.

En plus de rajouter les references il faudrait peut être changer les 1, 2 et 3 du texte en a, b et c comme cela on évitera tout problem

![siif presentation](https://cloud.githubusercontent.com/assets/16286544/11779247/349f052a-a25a-11e5-9a7f-e4c11b16942a.PNG)

**Comment by ndhuygelaere** [comment]
probably duplicate issue

**Comment by vincentgode** [comment]
Le texte de cette page a été changé dans une précédente issue. Il ne contient maintenant plus de points 1, 2 et 3.

![ss 2016-02-09 at 03 15 46](https://cloud.githubusercontent.com/assets/16646763/12918720/bd7f24c0-cf40-11e5-968f-84cecaffce4a.png)
