### ISSUE TITLE
Register title of SA sheet

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#281]
Please change the title in the SA sheet. This is not sensitive area reference 2012 but 2014

![register sa reference](https://cloud.githubusercontent.com/assets/16286544/19716109/2c50a672-9b5a-11e6-9812-dc169ffd8db5.GIF)

**Comment by bbondier** [comment]
Can't be automated. Do I remove the date altogether?

**Comment by Rakedjian** [comment]
removing the date is the best solution

**Comment by bbondier** [comment]
Done
