### ISSUE TITLE
Register SA criteria C

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#283]
In the Slovenian register there is no information concerning the starting date of application related to criteria c ((column W). This information is in the XML. Could you please add it in the table

![register sa title table](https://cloud.githubusercontent.com/assets/16286544/19716289/3f8c3b10-9b5b-11e6-9b68-5105e99f621d.GIF)

**Comment by bbondier** [comment]
Fixed, but requires a new data import to take effect.
