### ISSUE TITLE
FI WFD district in the discharge point

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#285]
What is strange in the discharge point fiche is that we don't have any information about the district even if the information is present in the  reporting file

http://webnuxdev.rnde.tm.fr/uwwtd_fi/discharge-point/fijvpp000000003189/2014

![linked wfd district](https://cloud.githubusercontent.com/assets/16286544/19734032/59bc4660-9ba6-11e6-96d9-b9b215e0a581.GIF)

**Comment by bbondier** [comment]
The xml field used to fill 'Linked River Basin District' is 'dcpReceivingWater'. This field is not present in the xml file. Should we use an other field?

**Comment by Rakedjian** [comment]
This is the parameter that has to be used and it is present in the XML dcpWFDRBD
http://dd.eionet.europa.eu/dataelements/76500

**Comment by cnassar** [comment]
fixed
