### ISSUE TITLE
CY Megabug compliance calculation

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#286]
It seems to be in agglomerations where there is no load connected and a huge part discharge without treatment

http://webnuxdev.rnde.tm.fr/uwwtd_cy/agglomeration/cy601-agglo/2014

It is absolutaly not possible with the hierarchical approach to have a situation of not compliant under Article 3 and not relevant concerning Article 4

The calculation for Article 4 and perhaps Article 5 compliance is totally false in Cyprus.

Has to be corrected urgently

**Comment by cnassar** [comment]
No problem with the legal conformity (Art. 3 = NC and Art. 4 =NR). However, the distance to compliance has to be at zero for Art. 4.
![image](https://cloud.githubusercontent.com/assets/22166796/20051365/fb8fac08-a4ce-11e6-846f-da9f11b83619.png)

**Comment by Rakedjian** [comment]
You are right. Distance to compliance has to be zero
