### ISSUE TITLE
Malta Sant Antnin Urban Wastewater Treatment Plan

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#287]
Why is this treatment plant not connected to Malta South agglo

http://webnuxdev.rnde.tm.fr/uwwtd_mt/?q=treatment-plant/mtsastp/2014

http://webnuxdev.rnde.tm.fr/uwwtd_mt/?q=agglomeration/mtms/2014

It seems to be connected in the XML file

![malta uwwtp](https://cloud.githubusercontent.com/assets/16286544/19775987/b548b5dc-9c72-11e6-805b-570a5d6b05f8.GIF)

What is missing is the discharge point. That's the issue but I don't understand why it has not been corrected before with ETC.

We also information related to the treatment in the XML but not in the treatment plant fiche but in the UWWTP treatment menu.

http://webnuxdev.rnde.tm.fr/uwwtd_mt/?q=uwwtps/treatment

![mt information uwwtp](https://cloud.githubusercontent.com/assets/16286544/19776266/ae8040c0-9c73-11e6-82d3-fb9b047ae9b7.GIF)

Why is this information not present in the explanatory note? This is a basic problem lack of connection to agglomeration and discharge point

**Comment by cnassar** [comment]
It is beacause the treatment plant has no discharge point. This issue is linked to the issue #376

**Comment by Rakedjian** [comment]
Yes and this is a specific case a treatment plant that is connected upstream to another treatment plant.

**Comment by bbondier** [comment]
Fixed
