### ISSUE TITLE
page d'accueil texte

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#29]
Je pense que l'on peut grosser la taille du texte sous la carte pour le render plus lisible. Mettre un espace après le dernier nombre et avant p.e.

![page d accueil texte](https://cloud.githubusercontent.com/assets/16286544/11779325/960218de-a25a-11e5-9108-e6623c56cbe4.PNG)

**Comment by ndhuygelaere** [comment]
taille du texte augmenté,espace ok et modification de la dimension des boutons pour qu'ils s'affcichent sur deux lignes
