### ISSUE TITLE
Register: "agglomeration level" sheet, line "compliance art. 4 only"

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#294]
Exemple : agglomeration of Aruküla in EE (code: eerka0370025)
this agglomeration must be C and not NC for compliance article 4 only, as the wwtp is complianant, and the not compliance comes from a problem of connecction.
 
![image](https://cloud.githubusercontent.com/assets/22166796/20052959/a64034cc-a4d6-11e6-904f-9f1dd7e021d5.png)

**Comment by bbondier** [comment]
Unfortunately, this column is filled with the aggart4compliance field of the agglomeration, calculated during conformity. According to Algo 11, this field now works hierarchicaly.

**Comment by friboben** [comment]
To be re-checked: the point relates to column "art4 only" where it should be compliant. column hierarchical is right.

**Comment by cnassar** [comment]
fixed
