### ISSUE TITLE
Platform: agglomerations equal to 2000 p.e.

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#295]
Agglomerations equal to 2000 p.e. are excluded from the statistical analysis and the maps of the platform.
However, there are counted in the register. We have to include those agglomerations in the satistical analysis of the platform. (or exclude them from the register one)
Benoit, can you give us your opinion about this issue ?

**Comment by friboben** [comment]
The UWWTD covers all what is 2000 pe and above, in all cases they have to be included. For maps it was corrected on some maps, has to be extended to all and also to all statistics asap.

**Comment by vincentgode** [comment]
Fixed. Tested for maps and statistics on uwwtd_it, uwwtd_at and uwwtd_dk.
