### ISSUE TITLE
Article 4 exemption in all countries Register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#297]
It is not possible to have in countries where there are no pending deadlines exemption concerning Article 4 due to transition period. In these countries the exemptions are mainly due to discharge in coastal waters. Pb of algorithm calculation of the summary table. The follow table belongs to NL

![exemption article 4 bug](https://cloud.githubusercontent.com/assets/16286544/20055717/d558b07a-a4e2-11e6-8499-0ee57c6fb1b0.GIF)

**Comment by friboben** [comment]
These agglomerations are exempted due to discharge in coastal water: treatment required = appropriate, hence treatment in place is not tested for art4. They should not be included in line "due to transition" : to be corrected.
