### ISSUE TITLE
3 first lines of "distance to compliance table" (connection)

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#299]
![image](https://cloud.githubusercontent.com/assets/22166796/20107496/00f275f8-a5d9-11e6-9a4f-eef5153a1121.png)
2 questions to Bruno and Benoit about the table distance to compliance.
1- Today, the line "target connection" includes only what is collected into collected system and treated thanks to IAS, but not the waste water discharged without treatment. Is this right, or should we include which is discharged without treatment (which means the whole generated load) ?
2 - Today, if an agglomeration is not compliant article 3, the whole generated load of the agglomeration is considered in the distance to compliance, and not only the part of the waste water that is discharged without treatment. Is this right, or should we consider only the part of the waste water that is discharged without treatment ?

**Comment by Rakedjian** [comment]
1 the distance to compliance concerning connection is only the load discharged without treatment very easy to calculate using the information from the agglomeration table. The target connection is the total load generated by the agglomeration. For Article 3, 4 and 5 the target load is the same target load than official compliance
2 Distance to compliance is not official compliance. As explained before this is only the part of the load directly discharged without treatment.

**Comment by bbondier** [comment]
Fixed
