### ISSUE TITLE
River basin district et agglomeration

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#30]
Je n'avais pas spécialement demandé de metre le river basin district au niveau des agglomerations considérant qu'il pourrait y avoir des cas où une partie de l'agglomération rejette dans un basin et une autre partie dans un autre. Je ne sais pas comment potentiellement le système gérerait cela. cette agglomeration serait elle dans les deux bassins?

Si cela apparait dans les deux pas de problèmes.

On garde cette approche on verra par la suite si cela pose des problèmes.

**Comment by ndhuygelaere** [comment]
A vérifier, mais la logique suivie est bien celle décrite : si une agglo est sur deux bassins alors elle apparaitera deux fois
