### ISSUE TITLE
Article 17 agglomeration website

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#300]
Please display all the information of the reporting in the specific window

In cyprus for example there is the date of completion of work that is missing. This is major information

http://webnuxdev.rnde.tm.fr/uwwtd_cy/agglomeration/cy52-agglo/2014

![article17 website](https://cloud.githubusercontent.com/assets/16286544/20131336/2053b914-a65d-11e6-99d6-c57f5c9c0db5.GIF)

![article17](https://cloud.githubusercontent.com/assets/16286544/20131342/25ecb010-a65d-11e6-99ba-c396f03e9e02.GIF)

**Comment by friboben** [comment]
OK, has to be added.
@Bruno: There seem also to have quality issue in dataset: 127.47€ is strange, name of EU fund 185 is strange, 9.4€ asked from EU fund is strange.

**Comment by Rakedjian** [comment]
this are millions euros,
