### ISSUE TITLE
installation in place calculation in BG

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#305]
We have three different numbers related to the monitoring result more stringent treatment 

when we calculate the total in the related column of the agglomeration level table of the register
when we have a look at what is written in the summary table of the register 
wen we have a look at what is written in the national chapter

I believe that the sum i calculated in the agglo level table of the register is the correct version. Please insure coherence.

total calculated in the agglo level table of the register

![installation in place agglo level](https://cloud.githubusercontent.com/assets/16286544/20175405/ddd7e074-a742-11e6-9e22-e17089a0ad27.GIF)

register summary table

![installation in place summary table](https://cloud.githubusercontent.com/assets/16286544/20175410/e221d43c-a742-11e6-8fd8-f8dc248dbc12.GIF)

National chapter table

![installation in place national chapter](https://cloud.githubusercontent.com/assets/16286544/20175418/e822be00-a742-11e6-9442-082180cc2c9d.GIF)

**Comment by cnassar** [comment]
@Rakedjian is this problem still relevant ?
We look to the updated register and check that the value match with the sum of the agglomeration level field "monitoring results f. more sting. OK".
![image](https://cloud.githubusercontent.com/assets/22166796/20342302/2b0efca0-abea-11e6-9efa-9a39bcced525.png)

**Comment by Rakedjian** [comment]
It seems to be ok now
Thanks
