### ISSUE TITLE
2% of the load not connected 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#306]
Reference to this question https://github.com/OIEau/uwwtd/issues/304

I come back to this issue because in fact MS report a percentage and not a load. It means that when  they have reported 2% it has to be compliant article 3. It seems to be not the case in the algorithm of the website but ok in the register.

**Comment by friboben** [comment]
see answer issue #304

**Comment by Rakedjian** [comment]
Ok
