### ISSUE TITLE
BG agglomeration without treatment plant

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#307]
Is it normal to have the message in read in this situation

https://github.com/OIEau/uwwtd/issues/306

Does it mean that there is problem in the aggloUWWTD table 

![agglo without uwwtp](https://cloud.githubusercontent.com/assets/16286544/20179194/33c90064-a755-11e6-9bca-54ef0212e94b.GIF)

**Comment by friboben** [comment]
link to treatment plant exist (NOTCON, ie no real treatment plant) but discharge point and receiving area is not provided as found in box "wastewater network connection", hence not possible to calculate compliance: seems to be mistake in dataset.
