### ISSUE TITLE
2% reopen

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#308]
I come back with the example of Plovidv

http://webnuxdev.rnde.tm.fr/uwwtd_bg/agglomeration/bgag5678400/2014

In the XML they reported 2%. It means that article 3 is compliant in the register and in the individual fiche of the website. It has no impact concerning the hierarchical approach for article 4 and 5.

Has to be corrected because that's not what we see in the register and in Bulgaria there are a lot of situation with 2% not connected and discharge without treatment.

![plovidv](https://cloud.githubusercontent.com/assets/16286544/20184186/1c4bc512-a768-11e6-8bbc-e78172e8347d.GIF)

**Comment by friboben** [comment]
solved.
