### ISSUE TITLE
QC agglomerations are not counted in the table "summary leagal compliance"

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#309]
![image](https://cloud.githubusercontent.com/assets/22166796/20261713/4e8cfb00-aa5f-11e6-9235-4ef71b6e9e96.png)
The exemple here is for Cyprus : only one agglomeration is connected to IAS, however, there is 4 agglomerations connected to IAS, but 3 of them are QC.
Those agglomerations have to been taken into account in this table.

**Comment by friboben** [comment]
I confirm: QC is when high % of IAS but is considered compliant, hence has to be included in the line, table to be corrected.

**Comment by cnassar** [comment]
Already fixed.
