### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#311]
Need to check and correct if necessary for 9th reporting that field "aggforecast" is used to put the date in box characteristics in line "Deadline connection compliance"of node agglomeration if provided, else use field "aggperiodover", and field "aggperiodover" is used to put the date in box characteristics in line "Deadline 2nd treatment compliance:" and "Deadline 3rd treatment compliance:".

**Comment by bbondier** [comment]
Fixed, new import required
@cnassar
