### ISSUE TITLE
Sensitive areas in Finland

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#313]
Why do we have two sensitive areas in finland
http://webnuxdev.rnde.tm.fr/uwwtd_fi/sensitive-areas

In the XML that is on eionet we have one SA
![sa finland reporting xml](https://cloud.githubusercontent.com/assets/16286544/20350060/75a5a17e-ac0d-11e6-807a-7c94a23ad72d.GIF)

This is this one that appears when we open the XML from this webpage
http://webnuxdev.rnde.tm.fr/uwwtd_fi/receiving-area/fi1/2014

But when we open the XML from this webpage 
http://webnuxdev.rnde.tm.fr/uwwtd_fi/receiving-area/beri10022rw/2014

we have another one that appears

![sa bis](https://cloud.githubusercontent.com/assets/16286544/20350219/4fc3676a-ac0e-11e6-8977-cab61cf35a02.GIF)

How is it possible to have two different contents related to the same file

Is there something missing in the finland database that was filled after. If it is the case we have to ask them to put the missing information

**Comment by friboben** [comment]
We correct this: the MS had reported 2 rca codes in file and refused to correct it. We have imported a first version of the file, found this, deleted and reimported but something went wrong: we delete all and reimport.

**Comment by friboben** [comment]
fixed
