### ISSUE TITLE
Agglomeration of 2000 p.e. 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#314]
Please be sure that agglomerations of 2000 p.e. appears in the websites. The belong to the reporting and have to be taken into account

This is not the case in Finland where there is not dot related to the following ones

http://webnuxdev.rnde.tm.fr/uwwtd_fi/agglomeration/fiykr12t0632/2014

http://webnuxdev.rnde.tm.fr/uwwtd_fi/agglomeration/fiykr12t0632/2014

**Comment by friboben** [comment]
agreed, I checked for one point and the agglomeration coordinates are provided and correctly located. To be checked for other platforms also.

**Comment by friboben** [comment]
fixed.
