### ISSUE TITLE
Size of the dots in Finland mapviewers

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#315]
The dots related to these mapviewers seems to be very small as regards what is displayed in other mapviewers

 http://webnuxdev.rnde.tm.fr/uwwtd_fi/uwwtps/compliance
http://webnuxdev.rnde.tm.fr/uwwtd_fi/uwwtps/treatment
http://webnuxdev.rnde.tm.fr/uwwtd_fi/discharge-points

**Comment by friboben** [comment]
fixed
