### ISSUE TITLE
Calculation of the concentration in Poland

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#317]
I wonder if there is not a mistake in the volume reported by Poland concerning each treatment plant. It seems to be a volume in m3/d and not m3/y. It explains why the calculation of the concentration is not coherent. I will raise this issue in the exploratory note.
They have also a problem with the load discharged that seems to be very high. 
http://webnuxdev.rnde.tm.fr/uwwtd_pl/treatment-plant/plmz0011/2016

**Comment by friboben** [comment]
Agreed, when making rough calculation with 150l/d per p.e. it comes to a range close to daily discharge. This problem is due to dataset provided, no IT issue here.
