### ISSUE TITLE
BE distance to compliance in the register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#319]
HAs to be checked why we don't have the same total for the performance that the sum that is calculated in the agglomeration sheet.

![be distance to compliance summary table](https://cloud.githubusercontent.com/assets/16286544/20599713/e8dae22e-b24f-11e6-8565-c1ce41fc3d5d.GIF)

![be distance 4](https://cloud.githubusercontent.com/assets/16286544/20599733/0a427738-b250-11e6-9e4f-ed7cf6ede103.GIF)

![be distance 5](https://cloud.githubusercontent.com/assets/16286544/20599735/0dedf66e-b250-11e6-91bf-380b7be6cf14.GIF)

For article 5 it seems that some agglomerations are not relevant related to this article  but have a distance to compliance because connected to  treatment plant that is connected to a bigger agglomeration. 

![exemple distance to compliance](https://cloud.githubusercontent.com/assets/16286544/20599860/d22d6ee2-b250-11e6-8e1d-391b623e90d2.GIF)

If we suppress this amount we obtain the amount in the summary table

For Article I have found no explanation

**Comment by bbondier** [comment]
Fixed
