### ISSUE TITLE
BE Hierarchical approach

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#320]
In the Belgium register we have a problem with the article 4 and 5 NC when Article 3 is not compliant. When it is only article 3 the compliance of the UWWTP only has not to be NC as it is in the register 

E.G WAVRE agglomeration

![article 4 and 5 hierarchical approach](https://cloud.githubusercontent.com/assets/16286544/20599984/8eb1cc3e-b251-11e6-8fb2-153d3521b02b.GIF)

**Comment by friboben** [comment]
Agree, case of Mouscron is correct but case of Wavre is false, should be C in column art4 only. To be checked and corrected.

**Comment by cnassar** [comment]
fixed
