### ISSUE TITLE
starting dates of SA in the agglomeration sheet of the register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#322]
This has still be done in the agglo sheet of the register and it is very relevant to check the deadline concerning Article 5 in countries that have a lot of SA. 

![sa register todo agglo](https://cloud.githubusercontent.com/assets/16286544/20619516/3fb0d9d2-b2f5-11e6-96a2-5ec802e3795e.GIF)

**Comment by vincentgode** [comment]
Fixed. Need re import xml files.

![screenshot 2016-12-09 04 05 21](https://cloud.githubusercontent.com/assets/16646763/21053553/36b96be2-be2a-11e6-9e9d-962c04a0d824.png)
