### ISSUE TITLE
Article 17 fiche order

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#324]
Could you please reorder the article 17 fiche following the order of the parameters reported. For example in the UWWTP you have the date of preparatory measure at the end of the list and not before the starting of works. The compliance samples has also to be after the compliance of works
http://webnuxdev.rnde.tm.fr/uwwtd_uk/treatment-plant/uksctp00050/2014

![article17 uwwtp fiche](https://cloud.githubusercontent.com/assets/16286544/20620689/321b0a4e-b2fb-11e6-9ab4-0336758295d3.GIF)

**Comment by vincentgode** [comment]
Hello,
Issue settled on uk website will be deployed on all sites next week.
