### ISSUE TITLE
Question about agglomerations not compliant in UK

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#325]
Why is these agglomerations not compliant?
There N and P removal in pllace and all the peformance are pass

http://webnuxdev.rnde.tm.fr/uwwtd_uk/treatment-plant/ukenanawtp000069/2014

http://webnuxdev.rnde.tm.fr/uwwtd_uk/treatment-plant/ukenanawtp000041/2014

http://webnuxdev.rnde.tm.fr/uwwtd_uk/treatment-plant/ukenanawtp000028/2014

There are other situation like that. It seems that criteria b applies in these SA

**Comment by friboben** [comment]
Agree, treatment N and P in place, and performance N and P are pass (while performance N is not to be tested as it is of type rcab)
Different issues:
sheet UWWTP: 
a) treatment met=no,
b) performance met=no,
c) compliance of treatment plant not visible (not calculated?), 
sheet agglomeration: compliance of related agglomeration NC for 3rd

**Comment by friboben** [comment]
settled, a combination was not present in the algorithms, see updated algorithms (red).
[UWWTD_SIIF_Phase III_ Task_I.1_compliance-algorithms-draft20.docx](https://github.com/OIEau/uwwtd/files/634537/UWWTD_SIIF_Phase.III_.Task_I.1_compliance-algorithms-draft20.docx)
