### ISSUE TITLE
UK deadline for article 5 in 2018

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#326]
There are some SA that were designated in 2011 with a deadline in 2018 that normally has to impact the compliance assessment for Article 5. 

This is the case for this agglomeration
 http://webnuxdev.rnde.tm.fr/uwwtd_uk/agglomeration/ukenmiagg000041/2014

that discharges in this SA:

http://webnuxdev.rnde.tm.fr/uwwtd_uk/receiving-area/ukenri152/2014

At this stage we will not change the assessment but perhaps UK will raise this issue

**Comment by friboben** [comment]
This would mean correct deadline for article 5 by reimporting date of application of the linked SA: needs a specific development.

**Comment by Rakedjian** [comment]
For this exercise we will not change the way to fill article 5.
Normally if the date is correctly filled in the database it will appear in the SA fiche. 
The issue is then to correct potentially manually in the database for a few number of agglomerations
My proposal will be to improve the agglomeration table in the future to include separate dates related to Article 3, 4 and 5 to be filled by MS.

**Comment by Rakedjian** [comment]
I have to raise this issue to EEA

**Comment by friboben** [comment]
I would suggest to first think of an improved display on SA fiche to correctly adress the genealogy issue, so that we can identify the necessary fields of information and only then discuss with EEA on exact needs.
