### ISSUE TITLE
UK sensitive area sheet

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#327]
Please be sure that all the information reported is displayed in the register
The starting dates of SA are very important and not present in the register

![staring date xml](https://cloud.githubusercontent.com/assets/16286544/20621781/201eab34-b300-11e6-8615-4e67b1107558.GIF)

![startind date register](https://cloud.githubusercontent.com/assets/16286544/20621787/23d0d176-b300-11e6-88dd-1697b8d19adf.GIF)

**Comment by friboben** [comment]
Bug: in column aP there are 2 values 0 and 1, in case 0, the starting date of application column is not filled. To be checked and corrected.

**Comment by vincentgode** [comment]
Fixed. Need to rebuild registers files.

![screenshot 2016-12-13 04 05 35](https://cloud.githubusercontent.com/assets/16646763/21145342/334e50ea-c14e-11e6-8500-838bcea32c79.png)
