### ISSUE TITLE
DE inactive agglomeration

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#328]
Is it possible to write inactive in the status of the title of the agglomeration. It has certainly to replace the 2 in the title. Has to be checked

http://webnuxdev.rnde.tm.fr/uwwtd_de/agglomeration/deagsn1203/2014

![inactive agglo](https://cloud.githubusercontent.com/assets/16286544/20631940/fe41d66e-b339-11e6-9a00-a0bc89513627.GIF)

**Comment by vincentgode** [comment]
Fixed

<img width="1206" alt="screenshot 2016-12-12 04 21 54" src="https://cloud.githubusercontent.com/assets/16646763/21104529/30a60d0a-c087-11e6-8478-6487c8ac3bfd.png">

**Comment by Rakedjian** [comment]
2 is temporary inactive

http://dd.eionet.europa.eu/dataelements/75959
