### ISSUE TITLE
DE Hierarchical approach Article 4 and 5

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#329]
There are several agglomerations that are not compliant due only to the difference between load connected and load entering the UWWTP. The UWWTP itself is compliant (article 4 or 5 only). It means that the not compliance Article 4 an d5 is only due to the hierarchical approach
This is not what is displayed in the register

![de article 4 only](https://cloud.githubusercontent.com/assets/16286544/20661302/64fa6e64-b54e-11e6-9109-0d858976cde7.GIF)

**Comment by friboben** [comment]
NO, in fact when there is a difference between load connected and load entering the UWWTP, it should be reported /added in columns compliance art4 / not compliant and if the agglomeration is relevant for art5 also added to columns compliance art5 / not compliant.

**Comment by Rakedjian** [comment]
You are right sorry

**Comment by friboben** [comment]
Should it be added in column "not compliant"?

**Comment by Rakedjian** [comment]
Yes this is what has to be corrected

**Comment by friboben** [comment]
To be corrected.

**Comment by friboben** [comment]
The calculation is not working well, for example for erfurt, it puts 0.2% and 672 pe in the column while the criteria is either 1% or 2000 pe and on the fiche we can see the real result which is 2652 pe and 0.8%.
http://webnuxdev.rnde.tm.fr/uwwtd_de/agglomeration/deagth8644/2014
Most probably the formula used are not correct.

**Comment by Rakedjian** [comment]
The idea is to put in the not compliant columns article 4 and 5 only the part of the load that is connected but not treated.  Has to be seen how to manage that in the most efficient way. In the distance to compliance this will be this part of the load that will be included. If it is to complicated we have perhaps to keep it as it is.
