### ISSUE TITLE
Centrage des textes dans les tableaux,

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#33]
Est ce possible de centre les textes pour plus de visibilité sans oublier les titres

![centrage information](https://cloud.githubusercontent.com/assets/16286544/11784602/8077c1b2-a27d-11e5-8be6-3e48120050f3.PNG)

**Comment by ndhuygelaere** [comment]
le faire en CSS, en jouant sur les index CSS
ex : 
/*cible le deuxième td de chaque tr*/
     tr td:nth-child(2){ ... }

**Comment by vincentgode** [comment]
Les textes et titres sont maintenant centrés sur les pages
- /agglomerations/compliance
- /agglomerations/connection
- /uwwtps/compliance
- /uwwtps/treatment
- /uwwtps/pressure
- /discharge-points
- /sensitive-areas
