### ISSUE TITLE
Agglo connected to a fictive UWWTP 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#331]
Under the datamodel it is requested to put the ID of the agglomeration when there is a  collecting systems without UWWTPs. It is the way to link both objects. Don't know if it is possible to manage that?

http://dd.eionet.europa.eu/dataelements/76970

There is no request not to fill UwwtpAgglos table in this case. 

In Portugal we have some situations where there is no link to UWWTP using the website but the link exists in the UWWTp table

http://webnuxdev.rnde.tm.fr/uwwtd_pt/agglomeration/ptagl426/2014

http://webnuxdev.rnde.tm.fr/uwwtd_pt/discharge-point/pt21583549/2014

http://webnuxdev.rnde.tm.fr/uwwtd_pt/treatment-plant/pt21506918/2014

The link is present here

![agglo without uwwtp link](https://cloud.githubusercontent.com/assets/16286544/20669182/0282ea70-b573-11e6-9201-5659589b893f.GIF)

**Comment by friboben** [comment]
In this case the code is ISCON, meaning the treatment plant exists. But the issue stems from the dataset: when node UwwtpAgglo is not provided, link between uwwtp and agglo is not possible as the data model allows 1-n agglo and 1-n uwwtp. Even if only 1 to 1 relation, the intermediate node has to be filled in.
There is an other case mentioned here: When no treatment plant, it is necessary still to have a link between agglo and uwwt, even if NOTCON, currently the tool is strictly linked to table uwwtpagglo, hence does not allow show missing TP and associated art17 info, could be adjusted (enhancement) to show also cases with no treatment pant (ideally the MS provides a XY in table uwwtp even if not present).

**Comment by Rakedjian** [comment]
You are right. MS have to report all the requested information to allow automation to work

**Comment by friboben** [comment]
In dd 3 fields for this table are mandatory, hence not clear why it is not reported and pointed as such by EEA/ETC http://dd.eionet.europa.eu/tables/9773
