### ISSUE TITLE
SA in PT

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#332]
There are only three SA in the register sensitive area sheet but in fact Portugal has more Sensitive areas. It seems that the SA that are reported are the less sensitive areas and not the sensitive areas

**Comment by friboben** [comment]
True, as can be seen here http://webnuxdev.rnde.tm.fr/uwwtd_pt/sensitive-areas 
BUT: The country did not report the field "Specialised Zone type Code" for most SA and the algorithm which calculates the register does not include the SA without specialised zone types.
In addition there are also a wide set of sensitive areas without agglomeration or TP, not sure why they are reported?

**Comment by Rakedjian** [comment]
Has to be requested clearly

**Comment by friboben** [comment]
This is the case (required), see http://dd.eionet.europa.eu/dataelements/77190
Not clear why the file is accepted at EEA/ETC level without this.
