### ISSUE TITLE
ES not compliant situation article 3

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#333]
There is an issue with the number of agglomerations not compliant with Article 3 and what is displayed i the summary table concerning agglomerations not connected and not treated. Have to check how it is calculated

If we have a look at the list we have 21 agglomerations that have discharges without connected and treatment
![spanish not compliant situation article 3](https://cloud.githubusercontent.com/assets/16286544/20720214/99b7c000-b65e-11e6-9a40-35dc1cc2681c.GIF)

and if we have a look at the summary table there is only 11 agglomerations. What is taken into account to arrive to these 11?

![summary table es](https://cloud.githubusercontent.com/assets/16286544/20720399/37210266-b65f-11e6-927b-8ff05a942933.GIF)

**Comment by friboben** [comment]
To be corrected, should consider all neither collected nor IAS.

**Comment by cnassar** [comment]
The table counts only the agglomerations that are C or QC regarding article 3. It is not all the agglomerations that dischage their waste water without treatment.
Can I close this issue ?

**Comment by Rakedjian** [comment]
Normally it is Ok if you consider only C and QC
