### ISSUE TITLE
SA in the Spain register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#334]
There is missing information related to the deadline in the SA register

We have this information in the reporting file 

http://webnuxdev.rnde.tm.fr/uwwtd_es/receiving-area/esri1013/2014

![sa spain deadline](https://cloud.githubusercontent.com/assets/16286544/20721007/9eadbd32-b661-11e6-923e-a458ee145764.GIF)

but not in the SA table of the register

![sa table of the register](https://cloud.githubusercontent.com/assets/16286544/20721000/99d11750-b661-11e6-834c-2b3b209f9b22.GIF)

**Comment by friboben** [comment]
Yes, has to be corrected.

**Comment by vincentgode** [comment]
Fixed.

![screenshot 2016-12-13 03 26 47](https://cloud.githubusercontent.com/assets/16646763/21143874/b3092414-c148-11e6-80dd-342f29a37bed.png)

**Comment by Rakedjian** [comment]
Seems to be ok now
