### ISSUE TITLE
distance to compliance summary table

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#335]
In the table related to the total there is missing information related to the target connection and monitoring result meet for more string treatment. It has to be corrected

![disatnce to compliance](https://cloud.githubusercontent.com/assets/16286544/20721160/36f5f33e-b662-11e6-8bcc-f02a82a07600.GIF)

**Comment by vincentgode** [comment]
Fixed.

![screenshot 2016-12-06 03 33 22](https://cloud.githubusercontent.com/assets/16646763/20929208/6ed50210-bbc9-11e6-99fc-977fde8cc248.png)
