### ISSUE TITLE
Agglomeration discharging in SA in Compliance summary table normal area

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#337]
I ha difficulties to understand how it is possible to have agglomerations concerned by Article 5 in the normal area summary table. Do we have some agglomerations that have several discharges ?

![normal area summary table](https://cloud.githubusercontent.com/assets/16286544/20752740/2f2c5836-b703-11e6-938a-cfdf4c4a484a.GIF)

**Comment by friboben** [comment]
This is a bug. In sheet normal area, the article 5 section should be empty: I suggest we delete all values and put grey colour in template.

**Comment by vincentgode** [comment]
Fixed. Need to re build register file.

<img width="510" alt="screenshot 2016-12-14 10 39 30" src="https://cloud.githubusercontent.com/assets/16646763/21177134/0cbcef62-c1ea-11e6-8031-52620be3aa35.png">
