### ISSUE TITLE
Graph compliance article 4

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#338]
There is a problem with the load that is taken into account in the statistic webpage for the official compliance article 4. This is the same load than for article 3 but only the load connected has to be taken into account and in countries like Lt there is a lot of IAS that have to be removed. 

http://webnuxdev.rnde.tm.fr/uwwtd_lt/stats/graphs

![article 3-4 compliance stat graph](https://cloud.githubusercontent.com/assets/16286544/20879468/3ad25ba2-bad4-11e6-8763-88df67f0c2c1.GIF)

**Comment by friboben** [comment]
To be corrected.
legal compliance for 2nd treatment in p.e. must consider all pending deadlines as not relevant, and the rest in compliant or not compliant categories, when no situation "PD", the values should be the same than in graph "Waste water treatement plant : Load entering by compliance".

**Comment by vincentgode** [comment]
Fixed. Need to rebuild register file.

<img width="576" alt="screenshot 2016-12-14 11 44 21" src="https://cloud.githubusercontent.com/assets/16646763/21179102/d00ecc08-c1f2-11e6-89d1-218291cb941d.png">
