### ISSUE TITLE
Romania Deadline

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#339]
The deadline in the register is 31/12/2015 for the agglomerations of more than 10 000 p.e.

How is it possible to have 31/12/2013 for article 3 and 31/12/2015 for Article 4 and 5
http://webnuxdev.rnde.tm.fr/uwwtd_ro/agglomeration/roag_137773/2014
![rodeadlinewebsite](https://cloud.githubusercontent.com/assets/16286544/20880683/7fdcf392-bad9-11e6-8cd3-8daa2b0e49e8.GIF)
![ro xml deadline](https://cloud.githubusercontent.com/assets/16286544/20880692/853b386c-bad9-11e6-9d6e-4cf630b1a174.GIF)

**Comment by friboben** [comment]
We used the field <aggforecast>, can you confirm the field aggperiodover has to be used for the 3 deadlines?

**Comment by Rakedjian** [comment]
I had a feedback from Chady that explained that there was an agreemnt with Romania and ETC to use another parameter for this date. If it is like that don't change anything
In the future I am going to propose a three parameters related to each Article for MS to put the real deadline if different. 
For the compliance assessment there is a need only to take into account the distance to compliance approach considering the target that is written in the accession treaty. Percentage of the total load for each Article
