### ISSUE TITLE
pb de tri sur bassin

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#34]
Je ne sais pas si en Irlande les codes basin sont bien des bassins parce que je trouve qu'il y en a beaucoup et pas beaucoup d'agglos par basin. De très nombreux codes renvoient une information vide beaucoup trop par rapport à une logique de basin.

http://webnuxdev.rnde.tm.fr/uwwtd/agglomerations/compliance?field_anneedata_value=2012&field_agggenerated_value_op=%3C&field_agggenerated_value[value]=&field_aggcompliance_value=All&field_aggart3compliance_value=All&field_aggart4compliance_value=All&field_aggart5compliance_value=All&field_regionnuts_value=All&field_dcpreceivingwater_value=IEWE_450_0000

Lorsque je tri avec le code IE01_1544 le champ tri disparait totalement. On est dans le cas où il n'y a pas de résultat mais le champ de tri ne devrait pas disparaitre. 

![tri bassin](https://cloud.githubusercontent.com/assets/16286544/11784683/00356b98-a27e-11e5-8da3-e49f1b320d12.PNG)

**Comment by ndhuygelaere** [comment]
Il y avait une erreur, en fait les codes correspondaient aux water bodies et pas aux RBD qui ne sont associés directement dans le rapportage. Désormais, l'appariement avec les RBD est réalisé via un croisement géographique.
Le tri fonctionne correctement depuis la dernière mise à jour.
