### ISSUE TITLE
Register France Article 54

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#340]
The rate of removal concerning article 5.4 is bad calculated.

It has to be 1- what is obtained. Please use a % like 76.57%
![article 54 fr](https://cloud.githubusercontent.com/assets/16286544/20881080/e7642bc4-bada-11e6-943a-5c803f91de9a.GIF)

**Comment by friboben** [comment]
two elements to correct: 
a) layout of excel: figure in %
b) formula used: (incoming-discharge)/incoming

**Comment by vincentgode** [comment]
Fixed

<img width="913" alt="screenshot 2016-12-06 01 37 30" src="https://cloud.githubusercontent.com/assets/16646763/20925818/5349223e-bbb9-11e6-8364-5c372d39bf30.png">
