### ISSUE TITLE
SA mapviewer FRance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#342]
designation date of this sensitive area with N parameter is missing. This date is in the register and certainly in the XML

http://webnuxdev.rnde.tm.fr/uwwtd_fr/receiving-area/fr_sa_cm_03207/2014

Information from article 54 is still missing with the load entering/discharge and the rate of removal

**Comment by friboben** [comment]
1) @Bruno: There is an issue in this case with what is currently displayed: date of designation 2006, date of application 1998, for non expert this may lead to un understanding: a suggestion for improvement of display?
2) for correction: "information missing" is calculated for 2012 here: http://webnuxdev.rnde.tm.fr/uwwtd_fr/receiving-area/fr_sa_cm_03207/2012, should be also visible for 2014.

**Comment by Rakedjian** [comment]
This is what happens in France because of the update of designation but also results of infringment procedure that's why it is so important to have both dates.

**Comment by friboben** [comment]
Then 2 corrections needed: 
a) information to display for parameters should consider for each parameter the relevant date, ie N, P, other and all possible combinations
b) information missing (see above)

**Comment by cnassar** [comment]
For the 8th reporting (2012) there is only four possible fields for dates in the XML file:
1) rcaDateArt58 (Starting date of application of Art. 5(8))
2) rcaDateDesignation (Last date of designation or revision/ in case Art. 5(8) and 5(2-3) is applied: Starting date of application of Art. 5(2-3))
3) rcaDateArt54 (Starting date of application of Art. 5(4))
4) rcaCDateOtherDirective (Designation criteria c - reference date of the area according to this Directive)
I then propose to apply the same date of desingantion for all the parameters that are at "true" (date n° 2) except for criteria c (date n° 4)
The dates n° 1  and n° 3 will be used as date of application for article 5(8) and article 5(4).
@Rakedjian  can you give me your confirmation ?

**Comment by friboben** [comment]
Do not forget the combination of fields which allows define what 
article(s) is/are applied for rca.

***********************************************************************************
Benoît FRIBOURG-BLANC
OIE/IOW (Office International de l'Eau/International Office for Water)
15 rue Edouard Chamberland
87065 LIMOGES Cedex, France
Tel. 33.5.55.11.47.97 ou/or 47.80
Mobile (France only): 06.82.72.28.06
Skype: fribourg.blanc
Fax 33.5.55.11.47.48
E.mail : b.fribourg-blanc@oieau.fr
web: http://www.oieau.org

***********************************************************************************
UWWTD SIIF national WEBSITES: IE: http://uwwtd.oieau.fr/ - CY: http://uwwtd.oieau.fr/cyprus/ -
LT: http://uwwtd.oieau.fr/lithuania/ - SI: http://uwwtd.oieau.fr/Slovenian/
HR: http://uwwtd.oieau.fr/croatia/ - PL: http://uwwtd.oieau.fr/poland/ - RO: http://uwwtd.oieau.fr/romania

Natural Water Retention Measures: http://www.nwrm.eu/

L'Office International de l'Eau se mobilise pour l'environnement - MERCI DE N'IMPRIMER CE COURRIEL QUE SI NECESSAIRE
International Office for Water is environmentally involved- THANK YOU FOR ONLY PRINTING THIS E-MAIL IF NECESSARY

**Comment by cnassar** [comment]
@friboben this part is already fixed. It need to redo import in order to be effective.

**Comment by Rakedjian** [comment]
For 8th reporting this is normal not to have all information because the starting dates were not requested
