### ISSUE TITLE
SA phosphorus only France

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#343]
It seems that information is missing concerning the phosphorus parameter that is 1 instead of zero and the date of application that is reported in the XML and display in the website

![sa phosphorus france](https://cloud.githubusercontent.com/assets/16286544/20888710/53e9db02-bb00-11e6-9644-09fecbd27d41.GIF)

**Comment by cnassar** [comment]
@bbondier need to check if the issue still relevant.

**Comment by cnassar** [comment]
fixed
