### ISSUE TITLE
Date format in SA fiche

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#346]
¨Please check again there is a not user friendly format concerning the begin life

When there is  date it is better to use 11/11/2011 as a format

![date format](https://cloud.githubusercontent.com/assets/16286544/20968647/afdce25c-bc85-11e6-9ee3-94dc7bf4f689.GIF)

http://webnuxdev.rnde.tm.fr/uwwtd_gr/receiving-area/grsatw03/2014

**Comment by friboben** [comment]
This is again an issue in the dataset provided: it is not normalised and some countries provide just DD/MM/YY, some the complete string with hour. In a usual data collection, such kind of errors are setteled during the QA/QC step. We need to add a filter in the presentation: enhancement.
