### ISSUE TITLE
0 in SA fiche

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#347]
Please check why there is zero for microbiology. It has to be either green or red

http://webnuxdev.rnde.tm.fr/uwwtd_gr/receiving-area/grsatw03/2014
![microbiology 0](https://cloud.githubusercontent.com/assets/16286544/20968784/6281ff64-bc86-11e6-93ec-c0c492aba072.GIF)

**Comment by friboben** [comment]
use filed <dd843:rcaParameterM>false</dd843:rcaParameterM>

**Comment by friboben** [comment]
Problem identified and corrected, will need to re-import all data for sensitive areas on each platfrom.
