### ISSUE TITLE
sensitive area page when article 5(4) applied

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#348]
The field "75% removal nitrogen and phosphorus" is wrong, However the country applies article 5(4).
![image](https://cloud.githubusercontent.com/assets/22166796/20976353/931a466a-bca2-11e6-8184-8fd07020d8d2.png)
http://webnuxdev.rnde.tm.fr/uwwtd_at/receiving-area/atra1cm/2014
Moreover, the field "microbiology" has a bad display: 0 instead of the icon.

**Comment by friboben** [comment]
field microbiology corrected see issue 347.

**Comment by vincentgode** [comment]
Field "75% removal nitrogen and phosphorus" fixed. Need reimport xml files.
