### ISSUE TITLE
Finland problem of calculation of compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#349]
Has to be checked if the new version of the website will correct the Not relevant situation in Finland for Article 4 and 5 that seems to be not normal with a global result of not compliance and the fact that some UWWTPS are declared Not compliant

http://webnuxdev.rnde.tm.fr/uwwtd_fi/agglomeration/fiykr12t0731/2014

http://webnuxdev.rnde.tm.fr/uwwtd_fi/agglomeration/fiykr12t0347/2014

**Comment by cnassar** [comment]
The WWTP are now not compliant because ther P_removal performance is at NR.
Is it OK for you @Rakedjian ?

**Comment by Rakedjian** [comment]
Ok
