### ISSUE TITLE
faire apparaitre les codes basin sur les listes sous les cartes

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#35]
Afin de faciliter le tri et aussi lorsque l'on télécharge la donnée est ce possible de faire apparaitre une colonne bassin.

Peux t'on avoir le meme ordre de colonnes sous la carte et sur la carte ?

![tri bassin liste](https://cloud.githubusercontent.com/assets/16286544/11784885/22f6191a-a27f-11e5-8765-34c6afc0ce31.PNG)

**Comment by ndhuygelaere** [comment]
ok en place
