### ISSUE TITLE
Romania distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#352]
Please check why there is a distance to compliance related to more stringent performance in timisoara

http://webnuxdev.rnde.tm.fr/uwwtd_ro/agglomeration/roag_155252/2014

![distance to compliance ro](https://cloud.githubusercontent.com/assets/16286544/21105389/52a5620e-c08a-11e6-9243-95ade01064a7.GIF)

When we have a look at the UWWTP it is totally OK

http://webnuxdev.rnde.tm.fr/uwwtd_ro/treatment-plant/ro5tm_528/2014

**Comment by friboben** [comment]
It has to be checked the algorithm for distance to compliance only consider N and/or P and not the other treatments because here we have UV and other and performance is at "not provided". For table distance to compliance, only N and/or P equipement and performance are to be used.
