### ISSUE TITLE
statistic view - agglomeration compliance map

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#36]
IL y a un pb d'affichage de la legend sur le camembert dans le cas paraticulier de l'Irlande. Le 9 de 945 989 disparait sous la couleur rouge du graph.

http://webnuxdev.rnde.tm.fr/uwwtd/stats/graphs

![agglomeration compliance graph stat](https://cloud.githubusercontent.com/assets/16286544/11785540/9b1e0314-a282-11e5-8cc3-3fa7586a10f1.PNG)

**Comment by ndhuygelaere** [comment]
The rendering have change (donutchart) and the issue is not one the new one
