### ISSUE TITLE
Article 5 compliance HU register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#360]
There is a problem of compliance calculation in Hungary related to Article 5. 

It seems that every is Compliant but the result is not compliant

![article 5 register hu](https://cloud.githubusercontent.com/assets/16286544/21178985/4d6354d6-c1f2-11e6-86c3-e5e3bbf51025.GIF)

**Comment by cnassar** [comment]
It seems to be solved. please tell me when you finish using the Hungarian platform in order to do the import and the conformity calculation.
