### ISSUE TITLE
SA fiche 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#361]
It has perhaps be already corrected. If not please have a look at the following remaining remarks concerning SA fiche

There is still an inversion for criteria drinking water and c in the SA fiche between designation data and starting data. There is still missing the designation date for criteria aN

the date concerning beginlife has to be in the same format than the other dates 

http://webnuxdev.rnde.tm.fr/uwwtd_ro/receiving-area/ro1/2014

![sa ro](https://cloud.githubusercontent.com/assets/16286544/21217040/741c2842-c2aa-11e6-9ac1-753dc16fb360.GIF)

**Comment by friboben** [comment]
see http://webnuxdev.rnde.tm.fr/uwwtd_ro/receiving-area/ro1/2014
corrected.
