### ISSUE TITLE
Compliance of timisoara

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#362]
Why has timosoara an other treatment declared

http://webnuxdev.rnde.tm.fr/uwwtd_ro/treatment-plant/ro5tm_528/2014

In the XML the is only UV and not "other" declared

![timis uwwtp xml](https://cloud.githubusercontent.com/assets/16286544/21221296/227198c0-c2bd-11e6-99b2-e04c36b850cb.GIF)

**Comment by friboben** [comment]
The issue was already identified and treated, a mistake in the import tool that needs reimport of all datasets. We wait resubmission and it will be settled by that, please ignore all cases with treatment more stringent "other" for the moment.
