### ISSUE TITLE
Distance to compliance eforie

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#363]
Why is the register Eforie and its treatment plant is not considered with performance more stringent installation in place. It is not possible to have zero for more stringent performance in the summary table. This is one of the agglomerations that has to considered in this table

http://webnuxdev.rnde.tm.fr/uwwtd_ro/agglomeration/roag_60464/2014

![eforie register](https://cloud.githubusercontent.com/assets/16286544/21221916/a61a1a92-c2bf-11e6-8418-becd8956f922.GIF)

**Comment by cnassar** [comment]
fixed
