### ISSUE TITLE
coordinate

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#365]
There is not only an issue with the coordinate in Austria but also in Romania

This is a clear example of pb of location. Check if it comes from their report or from the SIIF website. The yellow dots from the bottom to the top correspond to Tia mare, Cilieni, Rusanesti, Scariscoara and babiciu. There are all in the south, south est of the city

![pb coordinate](https://cloud.githubusercontent.com/assets/16286544/21225214/26e32b40-c2d0-11e6-9956-3014060f9594.GIF)

http://webnuxdev.rnde.tm.fr/uwwtd_ro/agglomeration/roag_128597/2014

**Comment by friboben** [comment]
This has to be checked but for the example given (rusanesti) if you go to homepage and zoom in, and go to latitude : 43.91000000 Longitude : 24.58000000 : values on bottom of map, you will see agglomeration dot should be 800m more in the north with these coordinates, which still is not the correct location, correct location being something like 43.94-24.59. This needs to sort 2 problems:
- has the country used ETRS89?
- is there a problem with google?
situation is not found in FR for instance as can be seen for TP of Limoges here 
![image](https://cloud.githubusercontent.com/assets/16597068/21226762/3e164b88-c2d7-11e6-9587-5c4fca68d98e.png)
