### ISSUE TITLE
Légende graph generated load by agglomeration size

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#37]
Une partie de la legend est cachée et les nombres sur les colonnes du graphique de gauche sont tronqués.

![legend load size](https://cloud.githubusercontent.com/assets/16286544/11785674/32547146-a283-11e5-9305-dea0b3cba5c3.PNG)

**Comment by ndhuygelaere** [comment]
tester sur Firefox, Chrome et IE sur site Irlande ==> ok depuis dernière mise à jour
