### ISSUE TITLE
SA 54 box in italy

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#370]
The article 54 box is no more readable

http://webnuxdev.rnde.tm.fr/uwwtd_it/receiving-area/itcm99csaq15001/2015

![sa 54 box](https://cloud.githubusercontent.com/assets/16286544/21255914/2e4530dc-c36f-11e6-8759-7878bf51686d.GIF)

**Comment by cnassar** [comment]
@Rakedjian can you check again please ?
If the issue still relevant, that meens that the problem come from the browser.
