### ISSUE TITLE
Article 54 Rate of removal in the register 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#372]
Is it possible to correct the calculation of the rate of removal for Article 54 in SA sheet of  the register ?
This is not the rate of removal that is displayed but the opposite.

![sa 54 rate of removal](https://cloud.githubusercontent.com/assets/16286544/21257128/874783ae-c376-11e6-8779-c7e26e3e7d9c.GIF)

Don't forget also to add the missing information in the final version such as number of UWWTPs and total capacity

**Comment by cnassar** [comment]
fixed
