### ISSUE TITLE
aggPeriodOver (aggPeriodOver) and  aggForecast (aggForecast)  for RO

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#374]
In Romania you have used period forecast to differentiate article 3 deadline and the other articles deadline

http://dd.eionet.europa.eu/dataelements/76015

Please don't do that for the other countries and specifically for Italy because it creates inconsistencies in the Article 3 deadline. It seems that Italy has used it more for Article 5 than for Article 3.

For Italy put only the information from aggPeriodOver for the deadline of the three articles

http://dd.eionet.europa.eu/dataelements/75990

These are two examples where there is this problem. When there is a false pending deadline it changes the calculation

http://webnuxdev.rnde.tm.fr/uwwtd_it/agglomeration/it150000000031/2015

http://webnuxdev.rnde.tm.fr/uwwtd_it/agglomeration/it1300000003/2015

You will have to regenerate the register in italy without this calculation before sending it or replace all the column D by the information of column E in the agglomeration table and E by F in the UWWTP table

We really have to improve the datamodel in the future to differentiate each deadline in an efficient way not like it is done currently.

**Comment by cnassar** [comment]
fixed
