### ISSUE TITLE
IT agglo discharging in SA

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#375]
This is the list of agglomerations or more than 10 000 pe that are discharging in SA

[IT AGGLO SA.xlsx](https://github.com/OIEau/uwwtd/files/657366/IT.AGGLO.SA.xlsx)

The sum of load is 29 002 903 that is much more than what is obtained in the summary table 9 780 273 and close to what was obtained in the last reporting. 
It is strange to find in the register so many NR article 5 situations as they are really discharging in SA

Is there a clear explanation for that?

**Comment by cnassar** [comment]
@bbondier need to add the condition ($dcp['rcatype'] == 'CSA' && $dcp['rca54applied'] === true) in the function uwwtd_rca_art54_applies (data_center.inc)
