### ISSUE TITLE
French website

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#377]
What happens with the French website? Why so many grey dots for the UWWTPs

http://webnuxdev.rnde.tm.fr/uwwtd_fr/uwwtps/compliance

![french website](https://cloud.githubusercontent.com/assets/16286544/21609587/9488d968-d1c3-11e6-95fd-6b9261b5b413.GIF)

**Comment by friboben** [comment]
Nothing special happens, the country decided to report agglomerations below 2000pe and the linked treatment plants. The datasets cannot be truncated from these agglomerations, as the choice is to use the official dataset reported by MS. To overcome this, the solution chosen for the maps for agglomerations was to filter out agglomerations <2000pe, but the maps on treatment plants are not filtered and show all UWWTP including those connected to agglomerations <2000pe. We may include in the list of enhancements to develop a filter to also not show those UWWTP on maps: it is not so trivial as agglomerations>2000pe may have UWWTP <2000pe.
