### ISSUE TITLE
menu cliquable de la carte de la page d'accueil

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#38]
Au niveau du menu de la carte de la page d'accueil ce serait bien de regrouper par theme. Les stations se trouvent tout en bas et les zones de baignade entre les agglomerations et les points de rejet

![menu carte page d accueil](https://cloud.githubusercontent.com/assets/16286544/11787847/245bb29c-a28e-11e5-985a-964ecc0a9a15.PNG)

**Comment by ndhuygelaere** [comment]
Pour action : mettre en place le behavoir "block switcher" et configurer le style du block => voir si dev nd

**Comment by bbondier** [comment]
Fixed
