### ISSUE TITLE
CY : Pb of graph calculation in number of agglomeration 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#383]
In the national chapter of Cyprus the first graph is False

You included the following result

![size in number of agglomeration](https://cloud.githubusercontent.com/assets/16286544/21639912/fed5f8b4-d272-11e6-95d9-6bf2cd4c5446.GIF)

When we have a look at the graph sheet of the register we have the following result that is correct

![cyp agglo number graph register](https://cloud.githubusercontent.com/assets/16286544/21639950/34a419f8-d273-11e6-9710-b69ef8be5897.GIF)

We have a total of 57 aglomerations that means the percentage concerning agglomeration 2000-10000 is 81% instead of 74%, agglomeration between 10001 and 100 000  16% instead of 23% and agglomeration of more than 100 000 4% instead of 2% and we have no difference between 2011 and 2014

I propose also to add a decimal because when we sum the percentage we have not 100%

**Comment by cnassar** [comment]
@Rakedjian 
I took this proposal into consideration.
However, adding a decimal will overcharge the graph, that is already veerry little in the register.
I will show you a first result in order to fix this problem

**Comment by Rakedjian** [comment]
Do your best. If not possible we will keep it as it is in the national chapter but in the register it is better to have the decimal
