### ISSUE TITLE
Finland SA

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#385]
Finland applies 58. Why is it not  displayed in the SA fiche

http://webnuxdev.rnde.tm.fr/uwwtd_fi/receiving-area/beri10022rw/2014

![finland sa](https://cloud.githubusercontent.com/assets/16286544/21674542/699e3f4c-d32e-11e6-8879-2587323afbd3.GIF)

In the XML we have 58523

![finland sa bis](https://cloud.githubusercontent.com/assets/16286544/21674552/7682b35a-d32e-11e6-9429-45cf0b00b206.GIF)

**Comment by cnassar** [comment]
Fixed
