### ISSUE TITLE
Ireland distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#387]
I have generated to new Ireland register and it seems that there is still a problem with the distance to compliance calculation

It is absolutely not possible to have 100% for more stringent treatment performance requirement. 

The numbers are different from the number we obtain in the Agglomeration level sheet

![ireland distance to compliance](https://cloud.githubusercontent.com/assets/16286544/21678382/cf2ef8fa-d33e-11e6-935a-9ef492afac8c.GIF)

**Comment by cnassar** [comment]
in the file register.inc, need to change 
"**if (isset($context['sandbox']['data'][$typedeadline]['morestringent_target']['total_load_pe']) && isset($context['sandbox']['data'][$typedeadline]['morestringent_target']['monitoring_result'])) {
                $context['sandbox']['data'][$typedeadline]['morestringent_target']['monitoring_result_distance_pe'] = $context['sandbox']['data'][$typedeadline]['morestringent_target']['total_load_pe'] - $context['sandbox']['data'][$typedeadline]['morestringent_target']['monitoring_result'];**"
by
"**if (isset($context['sandbox']['data'][$typedeadline]['morestringent_target']['total_load_pe']) && isset($context['sandbox']['data'][$typedeadline]['morestringent_target']['monitoring_result_distance_pe'])) {
                $context['sandbox']['data'][$typedeadline]['morestringent_target']['monitoring_result'] = $context['sandbox']['data'][$typedeadline]['morestringent_target']['total_load_pe'] - $context['sandbox']['data'][$typedeadline]['morestringent_target']['monitoring_result_distance_pe'];**"
