### ISSUE TITLE
IE register line 132 of Graph sheet

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#388]
There is certainly a mistake in the calculation in the register

It is not possible to have discharges without treatment when there is no discharge without treatment

![line 132 graph register](https://cloud.githubusercontent.com/assets/16286544/21681504/bcad4fcc-d34f-11e6-8fe3-e9837e849970.GIF)

**Comment by cnassar** [comment]
@Rakedjian 
Just to be clear : this value must be the load discharged without treatment + the difference between the connected load and the load entering the treatment plant. The performance/equipment of the treatment plant must not be taken into account. Is it right ?

**Comment by Rakedjian** [comment]
Yes you have to add the load not connected to collecting system and IAS and the load connected but not arriving to the UWWTP. The way to calculate the load not arriving to the treatment is by using UWWTPAgglos table parameter aucPercEnteringUWWTP. You compare the load declared to be connected in the Agglomeration table to this rate. If it is not the same it means normally that there is a discharge during transportation.

Don't try to use the load entering in the UWWTP table because you will generate fictive discharge.

**Comment by cnassar** [comment]
in the file register.inc the variable **$context['sandbox']['uwwtpinfo_for_agglo'][$uww_aggcode]['entering']** has the samevalue for each agglomeration (cf LU). Need to fixe this.
