### ISSUE TITLE
distance to compliance article 54

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#389]
We have still an issue with the calculation of distance to compliance in countries that apply article 54 about the installation in place more stringent

When we apply article 54 we don't care about the lack of more stringent treatment. It means that in a country like Netherland the distance to compliance concerning installation in place has to be zero. All these UWWTPs are equipped with secondary treatment; It means that it is correct. 

![distance to compliance article 54](https://cloud.githubusercontent.com/assets/16286544/21715446/cfe8d790-d404-11e6-8dd9-0b78c95aa1e3.GIF)

The calculation has also to be checked in France because there are several UWWTPs that are in article 54 sensitive areas

**Comment by cnassar** [comment]
Does it mean that the target for more stringent treatment must also be at zero ?

**Comment by Rakedjian** [comment]
No the target is the article 5 target but 100% is correct if there is no issue with secondary treatment

**Comment by cnassar** [comment]
Ok. What about if the compliance for article 5(4) is NC ? I assume that we have to count the whole connected load of the agglomeration in the distance to compliance (o maybe only the load discharged in a 5(4) sensitive area, if several article applied).

**Comment by Rakedjian** [comment]
It is only possible to apply article 54 if they give the load information and the rate calculation shows that it works (more than 75% for N and P)
If it doesn't work we don't consider article 5.4

**Comment by cnassar** [comment]
My point was on the agglomerations that apply article 5(4) and are not compliant regarding Article 5. Should we count their connected load in the distance to compliance ? (the right side of the table).

**Comment by Rakedjian** [comment]
Your question is about agglomerations in SA under article 54.

If they are not compliant article 5 it means that they are not compliant article 4 or 3. In this situation the load has to be included in the distance to compliance calculation
