### ISSUE TITLE
SK distance to compliance register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#391]
There is still an issue in the distance to compliance calculation for the pending deadline in the register

The summary table is empty 
![sk distance to compliance](https://cloud.githubusercontent.com/assets/16286544/21762449/f8b5022e-d658-11e6-86c6-cfe7daf20d61.GIF)

but there are some agglomerations that are not compliant

![distance to compliance agglo table hu](https://cloud.githubusercontent.com/assets/16286544/21762455/fccd594c-d658-11e6-9068-63833341dbb2.GIF)

**Comment by cnassar** [comment]
fixed
