### ISSUE TITLE
SK article 5 total target load

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#392]
In the register and in the analyse it is not possible to have more load connected for article 5 than for article 4

There is an issue in the article 5 calculation for the NR situation. This is what we have in the register in the graph sheet
![graph article 5 compliance cz](https://cloud.githubusercontent.com/assets/16286544/21763409/0d60ce7e-d65e-11e6-8990-7f996c2c843c.GIF)

and what we see in the national chapter with article 5 bar higher than article 4 in 2014

![hirstorical compliance sk](https://cloud.githubusercontent.com/assets/16286544/21763436/33273396-d65e-11e6-97f0-c6f035821f45.GIF)

**Comment by cnassar** [comment]
fixed
