### ISSUE TITLE
Distance to compliance UWWTP sheet in the register

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#398]
It seems that there is a pb when a UWWTP is connected to several agglomerations and one of them is more than 10 000 pe; It attributes a distance to compliance for Article 5 to the agglomerations below 10 000 pe.

There is no pb in the website

http://webnuxdev.rnde.tm.fr/uwwtd_sk/agglomeration/ska1080242/2014

But a problem in the UWWTP sheet

![distance to compliance article 5](https://cloud.githubusercontent.com/assets/16286544/21979860/0dc2d334-dbe1-11e6-8532-348066dee9b5.GIF)

**Comment by cnassar** [comment]
fixed
