### ISSUE TITLE
Compliance rate article 3 official SK

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#400]
Issue already raised that does not influence the calculation but the result in the table

The rate of compliance article 3 in the summary table has to be compared to the target and not the total load generated
It seems that only the result that is in yellow has to be corrected for Article 3. The other seems to be well calculated. In this case it has to be 100%

![percentage compliance article 3 rate](https://cloud.githubusercontent.com/assets/16286544/22149263/15305bfc-df13-11e6-8a46-580767b73b63.GIF)

**Comment by cnassar** [comment]
fixed
