### ISSUE TITLE
Missing distance to compliance more stringent performance result total

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#401]
There is a missing total for the addition of expired and pending deadline concerning distance to compliance monitoring results meet more stringent performance in the SK register; In this case the value is not 0

![distance to compliance total sk](https://cloud.githubusercontent.com/assets/16286544/22149450/2b7649e8-df14-11e6-8044-fd30676e03c3.GIF)

**Comment by cnassar** [comment]
fixed
