### ISSUE TITLE
Distance to compliance comparing result from Agglo table and summary table SK

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#402]
It is not a big problem because the values are closed and certainly due to calculation. At this stage no need to change any rules

We have a small difference when we add the information in article 3 Z column, Article 4 AQ and AS columns and Article 5 columns BY and CA with the result in the summarize table

For example with SK the sum in the Z column for expired deadline distance to compliance gives 17 002 for connection instead of 16 948 in the summary table

The sum in the AG column for article 4 gives 38 338 instead of 38 381 in the summary table

The sum in the AS column for article 4 gives 63 934 instead of 63 976 in the summary table

The sum in the BY column for article 5 gives 1 299 495 instead of 1 299 535 in the summary table

The sum in the CA column for article 5 gives 751 885 instead of 751 884 in the summary table

**Comment by cnassar** [comment]
fixed
