### ISSUE TITLE
distance to compliance performance secondary in Lithuania

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#406]
There is only one UWWTP that have the performance COD fails and that is linked to an agglomeration with a connected load of 3 510 pe

In the sumarrize table we have 5 665.

Where does the difference comes from

There is certainly also a missing calculation for more stringent monitoring result in this expired table such as in the total table

![pending deadline lt article 4](https://cloud.githubusercontent.com/assets/16286544/22152852/ff889d20-df24-11e6-92ef-c4bf47767643.GIF)

**Comment by cnassar** [comment]
fixed
