### ISSUE TITLE
algorithme compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#41]
Nouveau problème sur l'algorithme en Slovénie

http://uwwtd.oieau.fr/slovenia/agglomeration/si20007/2012

Pas possible d'avoir NR sur connection et non conformité sur 2nd treatment and 3rd treatment de plus on a des dates de conformité en 2015 donc tout devrait être NR.

![compliance slovenia](https://cloud.githubusercontent.com/assets/16286544/11793233/aef3360c-a2aa-11e5-9606-6844f7f8daf9.jpg)

![compliance slovenia bis](https://cloud.githubusercontent.com/assets/16286544/11793241/b82b826a-a2aa-11e5-8c3f-acafe2a5c178.jpg)

**Comment by ndhuygelaere** [comment]
Eric, je pense que tu as déjà corrigé ce point, tu peux fermer si c'est le cas.

**Comment by evincentoieau** [comment]
Benjamin a corrigé ça cette semaine.
