### ISSUE TITLE
distance to compliance monitoring results more stringent Estonia

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#412]
What is displayed in the summary table for distance to compliance more stringent monitoring result is false

![distance to compliance estonia](https://cloud.githubusercontent.com/assets/16286544/22372452/10b491e4-e49d-11e6-8567-26497f9db133.GIF)

**Comment by cnassar** [comment]
Is it ok now ?
![image](https://cloud.githubusercontent.com/assets/22166796/22459311/562a0104-e7a0-11e6-9e7f-a81e09d28832.png)
