### ISSUE TITLE
IE distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#414]
Don't know if the new version of the algorithm as solved this problem but there is a high difference for the monitoring results when we sum the distance to compliance more stringent treatment monitoring result in the agglomeration table (2,637,025 pe) and when we look in the summary table (3,545,906 pe)

The sum in the agglo table

![sum agglo ie and sumarize distance to compliance](https://cloud.githubusercontent.com/assets/16286544/22425722/c91b9154-e6fc-11e6-9597-4c4ed1c0697a.GIF)

Summary table in the register

![summary distance to compliance ie](https://cloud.githubusercontent.com/assets/16286544/22425754/ede2a36a-e6fc-11e6-8168-7dd4ea3a8f2c.GIF)

**Comment by cnassar** [comment]
fixed
