### ISSUE TITLE
LV distance to compliance agglo inf 10 000

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#415]
In Latvia there is a distance to compliance for at least one agglo below 10 000 pe. That's not normal to have that in the agglomeration table

![disatnce to compliance for agglo inf 10 000 eh](https://cloud.githubusercontent.com/assets/16286544/22426594/2243d9be-e700-11e6-914c-c23ec6f3bfd5.GIF)

Link to the agglomeration in the website

http://webnuxdev.rnde.tm.fr/uwwtd_lv/agglomeration/lv80175/2014

**Comment by cnassar** [comment]
fixed
