### ISSUE TITLE
Luxembourg target

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#416]
Why has the target article 3, 4 and 5 changed in Luxembourg? 
For article 3 it has to be 606 215
For article 4 it has to be 601 924
For article 5 it has to be 449 834
Where is the missing load?

For article 5 the load correspond to Bettembourg 

![target luxembourg](https://cloud.githubusercontent.com/assets/16286544/22428173/58c69606-e706-11e6-895a-0bfdf115e5d5.GIF)

**Comment by cnassar** [comment]
There was a problem in the compliance calculation.
The problem is now solved.
![image](https://cloud.githubusercontent.com/assets/22166796/22458476/ffddaa2e-e79c-11e6-8f34-4f62e4c8a0fe.png)
