### ISSUE TITLE
Distance to compliance other in PT

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#417]
We are here in situations where several agglomeration are compliant concerning article 5 but a distance to compliance appears related to the treatment in the agglomeration table. It is not possible to have that

This is one of the hyperlink in the table below. It seems to be due to situation where only other is requested

http://webnuxdev.rnde.tm.fr/uwwtd_pt/treatment-plant/pt9033032/2014

![distance to compliance pt compliant](https://cloud.githubusercontent.com/assets/16286544/22457698/2ec4ee00-e799-11e6-91af-6ad671a168e3.GIF)

**Comment by cnassar** [comment]
fixed
