### ISSUE TITLE
PD in spain ?

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#419]
Why are  these agglomeration under pending deadlines article 4 in the agglomeration table of the register and in the website ? There is no reason for that

http://webnuxdev.rnde.tm.fr/uwwtd_es/agglomeration/es3330170000000/2014

http://webnuxdev.rnde.tm.fr/uwwtd_es/agglomeration/es4070080002010/2014

http://webnuxdev.rnde.tm.fr/uwwtd_es/agglomeration/es1180870004011/2014

http://webnuxdev.rnde.tm.fr/uwwtd_es/agglomeration/es3330442501013/2014

http://webnuxdev.rnde.tm.fr/uwwtd_es/agglomeration/es3330764101010/2014

![pd in spain 4](https://cloud.githubusercontent.com/assets/16286544/22465595/ca6377c8-e7bc-11e6-8c15-e29d4a488544.GIF)

**Comment by bbondier** [comment]
Fixed
