### ISSUE TITLE
Distance to compliance calcul

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#42]
Le calcul de distance to compliance pour traitement secondaire et traitement plus rigoureux ne correspond pas à la réalité. Ce calcul ne doit se faire que par rapport à la charge connectée.

On n'a aucune donnée sur la station comment peut on avoir les performances bonnes sur traitement plus rigoureux. 

http://uwwtd.oieau.fr/slovenia/agglomeration/si20007/2012
http://uwwtd.oieau.fr/slovenia/treatment-plant/si_agg_20007/2012

![compliance slovenia](https://cloud.githubusercontent.com/assets/16286544/11793340/67eddbda-a2ab-11e5-9522-41eb5552a156.jpg)

**Comment by ndhuygelaere** [comment]
ok, corriger sur le site dev --> vérification en cours par BFB
