### ISSUE TITLE
Agglomerations that must have not distance to compliance more stringent

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#424]
this is the list of the agglomeration that normally don't have a distance to compliance value either because they have a size of 10 000 pe or below either because they are discharging in normal area

This is the link to two of them

http://webnuxdev.rnde.tm.fr/uwwtd_es/agglomeration/es11060100001010/2014

http://webnuxdev.rnde.tm.fr/uwwtd_es/agglomeration/es12360220109010/2014

![agglomeration nr for article 5](https://cloud.githubusercontent.com/assets/16286544/22466576/2dfb581a-e7c1-11e6-818f-40aa375440d0.GIF)

**Comment by bbondier** [comment]
Fixed
