### ISSUE TITLE
Pb of situation of the new legend

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#431]
There is a pb with the new legend button that hides some the apply/reset buttons in the UWWTP compliance map

![legend situation](https://cloud.githubusercontent.com/assets/16286544/22927738/3fe57874-f2b3-11e6-89bc-ab484c3e7c53.GIF)

**Comment by friboben** [comment]
settled for SE, if occurs for some others, just inform us and we will empty cache.
