### ISSUE TITLE
National platform : last modifications before the publication

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#432]
1) Keep the yellow headband on the home page but replace the message by "Version Beta : remaining inconsistencies are possible. They will be corrected during the next reporting exercise"
2)  The title of the national platforme: replace "UWWTD SIIF [MS] National Node" by "European Commission urban waste water website: [MS]"

**Comment by ndhuygelaere** [comment]
done

**Comment by friboben** [comment]
In English the correct wording is "Beta version"

**Comment by Rakedjian** [comment]
Ok
