### ISSUE TITLE
Home website : last modifications before publication

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#433]
1) Changes in the titles and descriptions:
**European national urban waste water websites**
For each European Member State you can access to their urban waste water reporting information (by maps, lists, statistics, graphs) via the following websites
**Development**
You can follow SIIF improvements, download and install your own SIIF website on the Git Space

**Comment by ndhuygelaere** [comment]
text was changed

**Comment by Rakedjian** [comment]
Ok
