### ISSUE TITLE
Replace the first paragraph of the 

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#434]
The Structured Implementation and Information Framework (SIIF) concept is the result of a European Commission (Environment Directorate General) pilot project essentially focused on the organisation and management of data under the [urban waste water treatment directive ](http://ec.europa.eu/environment/water/water-urbanwaste/index_en.html)91/271/EC (UWWTD). The objective is to enhance the reporting process and the generation of information for policy makers, interested parties and the general public.This concept is in line with the requirements of the [Public Access to Environmental Information](http://ec.europa.eu/environment/aarhus/legislation.htm) and [INSPIRE](http://inspire.ec.europa.eu/) Directives. This IT development received an [international excellence policy Award](https://www.geospatialworld.net/news-posts/geospatial-media-communications-announces-winners-geospatial-excellence-award/) in January 2017.  

[More information about the SIIF](http://uwwtd.oieau.fr/node/4)
[Video about the SIIF](https://youtu.be/lvmn6ZynL1I)

**Comment by cnassar** [comment]
Do you mean the first paragraph of the press release ? (on the OIEAU website)

**Comment by Rakedjian** [comment]
No the first paragraph of the website

http://uwwtd.oieau.fr/
 
![welcome text](https://cloud.githubusercontent.com/assets/16286544/24092088/64841c9a-0d4c-11e7-8f75-17982933bcf4.GIF)

**Comment by friboben** [comment]
Done
