### ISSUE TITLE
REGISTER UWWTP change of entering load and capacity

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#47]
Dans le cas de l'Irlande on a 0% de changement de capacité et pas d'information pour le changement de charge entrante. Il y a donc une erreur sur la formule pour la capacité et nécessité lorque l'on ne peut pas faire le calcul d'indiquer "NI" no information. D'autre part changer la legend de (1) par  "cell orange when the difference is more than 20%" et supprimer (2) et sa legend. En profiter pour supprimer (3) et (4) et leurs légendes qui étaient des indications pour developer le fichier

![registeruwwtpchange capacity](https://cloud.githubusercontent.com/assets/16286544/11843717/5e26e69e-a40b-11e5-8594-15062bb9a166.PNG)

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
