### ISSUE TITLE
catalogue inactive for all websites: urgent to re-activate for uwwtd.eu

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#471]
The catalogue is not accessible, probably due to https protocol on uwwtd.eu, in following example we arrive to error page: http://www.uwwtd.oieau.fr/services/ows/?service=WFS&version=1.1.0&request=GetFeature&typeName=UWWTD:UWWTD_Luxembourg_ReceivingArea&CQL_FILTER=UWWTD:repReportedPerdiod=2014 
This has to be corrected for production website as a minimum, and if possible also on dev websites.

**Comment by ndhuygelaere** [comment]
Catalog was only unavailable for http**s** link and for www.uwwtd.oieau.fr domain. Adress without www were ok.
Webserver is now well set with www adress and redirect to uwwtd.eu
