### ISSUE TITLE
REGISTRE UWWTP total change of capacity

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#48]
Mettre une décimale après la virgule pour le pourcentage total. 

Comment est ce possible pour l'Irlande d'avoir 15.1% de difference entre les charges entrantes alors qu'il n'y a aucun information sur la période précédente.

![registeruwwtptotalchange](https://cloud.githubusercontent.com/assets/16286544/11845540/ba70ad64-a414-11e5-9e36-9040d02b1299.PNG)

**Comment by bbondier** [comment]
Fixed
