### ISSUE TITLE
Bug on filter criteria on discharge point page

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#484]
When one select an option not valid for the country, the result show map of an other country, ex: https://dev.oieau.fr/uwwtd_dk/discharge-points?field_anneedata_value=2016&zonetype=A54&rcacat=All
When looking at the table: discharge points which are inactive and linked to a treatment plant have compliance pending deadline, discharge points which are inactive and not linked to a treatment plant have no compliance information: both should be identified as "inactive" in last column.

**Comment by ndhuygelaere** [comment]
not really a bug, just an empty search => now the case is managed
