### ISSUE TITLE
REGISTRE UWWTP Chypre

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#49]
Au niveau du Feuillet stations il manque la moitié des stations. Il s'agit des agglomerations avec 100% de rejets directs qui ne sont pas générées dans la liste mais qui doivent être dans la liste.

Voici le registre original

![registreuwwtpcyprusoriginal](https://cloud.githubusercontent.com/assets/16286544/11846537/5cbb8716-a419-11e5-9381-e852f6b80ba4.PNG)

et le register généré par le site

![registreuwwtpcyprusnew](https://cloud.githubusercontent.com/assets/16286544/11846550/6935558a-a419-11e5-9eae-b5e2a57a4250.PNG)

**Comment by evincentoieau** [comment]
Oui, dans la feuille station ne sortent que les station/agglo qui existe dans la table UwwtpAgglo.
J'ai ajouté les agglomérations manquante (celles qui ne sont pas dans la table UwwtpAgglo).

fait mais pas encore en production.
