### ISSUE TITLE
compliance algorithm and the specific case of Estoril

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#491]
[UWWTD_SIIF_compliance-algorithms-v22.docx](https://github.com/OIEau/uwwtd/files/2795773/UWWTD_SIIF_compliance-algorithms-v22.docx)
one specific case in PT: Costa do Estoril agglomeration (aggID code: PTAGL070, uwwID: pt12058222) has a derogation granted according to Article 5(8) of the Urban Waste Water Treatment Directive (Commission Decision 2001/720/EC of 8.10.2001, OJ L269 of 10.10.2001). For this agglomerations it is required a less stringent treatment, ie treatment required=primary treatment.
Algorithms for LSA have to be changed (p4 of pdf, last case right, add a test after generated load >150000, answer no, test generated load>10000, yes required = primary, no required = appropriate
it is on p4 of herewith doc, and there is also an other update (simplification) to implement on p8 (if not already)

**Comment by ndhuygelaere** [comment]
ok special case added in algo
