### ISSUE TITLE
view stat slovenie, graph agglomeration by compliance

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#493]
Pas clair pourquoi pending en 2012 et NR en 2014 alors que la deadline est 2015 donc devrait plutôt être aussi pending en 2014: 
![image](https://user-images.githubusercontent.com/16597068/52472692-33757280-2b94-11e9-8c62-d960eddd7762.png)

**Comment by ndhuygelaere** [comment]
Test re-import and reprocessing compliance and the result is the same, maybe some data are missing
