### ISSUE TITLE
calculation of register: issue on type of SA considered for calculation

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#505]
In 3 countries applying Article 5(8) & 5(2,3): DK, DE, FI, the register does not calculate the compliance art5. It seems to come from column F in sheet agglomeration level because the country has not provided the aggDateart5 : "This value is required for all active agglomerations of size ≥ 10 000 p.e., served by UWWTPs discharging into sensitive areas." http://dd.eionet.europa.eu/dataelements/94187. This create an issue because then art5 compliance in columns AT-BV lands in "Pending Deadline (PD)" and is then disturbing the register calculation.

**Comment by ndhuygelaere** [comment]
bg fixed during the data import : if the date is missing for art5, we use the main deadline date
