### ISSUE TITLE
register calculation: summary distance to compliance for DK

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#506]
in DK 2 agglomerations are not compliant art5. https://dev.oieau.fr/uwwtd_dk/agglomerations/compliance?field_anneedata_value=2016&field_agggenerated_value_op=%3C&field_agggenerated_value%5Bvalue%5D=&field_aggcompliance_value=All&field_aggart3compliance_value=All&field_aggart4compliance_value=All&field_aggart5compliance_value=NC&field_regionnuts_value=All&rbd=All
but in sheet summary distance to compliance the result for more stringent treatment target, installation and monitoring are the same: this is not possible!

**Comment by ndhuygelaere** [comment]
"just" a data import bug cause by a widely shortcut, I replay all the process and the bug disapear
