### ISSUE TITLE
REGISTRE UWWTP sigles receiving water

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#51]
Remplacer les codes par les expressions

CW	to coastal water
ES	to estuary
FW	to freshwater
LC	on land (catchment of coastal water)
LF	on land (catchment of freshwater and / or estuary)
CW	to coastal water
ES	to estuary
LC	on land (catchment of coastal water)
LF	on land (catchment of freshwater and / or estuary)

IR : irrigation
IN: infiltration

**Comment by bbondier** [comment]
Done.
