### ISSUE TITLE
sensitive area 5(4): issue in box description

### ISSUE THREAD

**Issue by friboben** [OIEau/uwwtd#510]
On page https://dev.oieau.fr/uwwtd_it/receiving-area/itcm99csaq15001/2016 in the box Description, the value Number of UWWTPs is reporting about 7200 UWWTP while the summary table report 1521
https://dev.oieau.fr/uwwtd_it/sensitive-areas?field_anneedata_value=2016&tot_design_capacity_op=%3C&tot_design_capacity%5Bvalue%5D=&tot_entering_load_op=%3C&tot_entering_load%5Bvalue%5D=&rca52_art=All&rca54_art=1&rca58_art=All&zonetype=All&zonetype_spe=All
probably a double counting. Necessary to check also the other figures of the box.

**Comment by ndhuygelaere** [comment]
not a bug, it's the real value in the XML data file
