### ISSUE TITLE
REGISTRE UWWTP per of generated load entering and load entering

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#52]
Les données pour Chypre ne correspondent pas aux données rapportées. Par exemple pour Kakopetria la charge entrante est de 1200 p.e. et ici on a 576 p.e.. Le pourcentage n'est pas bon. Il devrait être de 48%. On a 23.04%.

http://uwwtd.oieau.fr/cyprus/treatment-plant/cy110_uwwtp/2011

Du coup il serait utile de rajouter deux champs pour verifier la coherence entre les données sortant de la table UwwtpAgglo et celles de la table UWWTP. 

La première colonne serait le pourcentage de la charge générée entrant dans la station d'après la table UwwtpAgglo. La deuxième colonne le calcul de la charge entrante d'après ce pourcentage. La troisième colone le calcul du pourcentage d'après la charge entrante de la 4ème colonne correspondant à la charge déclarée dans la table UWWTP. On aurait ainsi un moyen de verifier la coherence entre ces nombres.

![registreuwwtpentering load](https://cloud.githubusercontent.com/assets/16286544/11865921/b315ca20-a4a7-11e5-923b-e134fe7c225e.PNG)

![kakopetrialoadentering](https://cloud.githubusercontent.com/assets/16286544/11865959/0f5a501c-a4a8-11e5-8057-d2e3b016c6f3.PNG)

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
