### ISSUE TITLE
registreUWWTP nombre de points de rejets

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#53]
Visiblement à Chypre on a plusieurs stations qui ont plusieurs points de rejets; Je pensais cette situation très rare mais avec la reuse cela risque de se multiplier. Est ce possible de rajouter les deux colonnes qui existaient dans le register d'origine

![registreuwwtpnumberdischarge points](https://cloud.githubusercontent.com/assets/16286544/11867195/d16d7ff6-a4af-11e5-83d3-87a759783248.PNG)

à la fin des colonne sur le milieu de rejet

![regsitreuwwtpnumberdischargepointbis](https://cloud.githubusercontent.com/assets/16286544/11867253/2a71cd28-a4b0-11e5-9240-819e101be90c.PNG)

**Comment by bbondier** [comment]
This implies considerable work. We should postpone this feature to a future contract.

**Comment by Rakedjian** [comment]
OK
