### ISSUE TITLE
register UWWTP treatment in place

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#55]
On ne peut avoir le traitement en place 1 que si on a 1 sur le traitement et 1 sur les performances

![registeruwwtptretamentinplace](https://cloud.githubusercontent.com/assets/16286544/11869808/c8ad98c0-a4c2-11e5-8092-0fc155a3f43f.PNG)

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
