### ISSUE TITLE
UWWTP registre pourcentage d'élimination

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#56]
Pas possible d'avoir un pourcentage de 100% avec des zero dans la colonne average incoming et average discharge

![registreuwwtp percentage removal](https://cloud.githubusercontent.com/assets/16286544/11870157/6817fc32-a4c5-11e5-8926-46a755852c8e.PNG)

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
