### ISSUE TITLE
REGISTRE UWWTP monitoring lithuania

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#58]
Pour le calcul de la conformité article 5 on doit avoir le traitement en place et le monitoring correct

Dans le cas lithunian ci dessous on a bien pass pour performance other, on a bien traitement other et rien dans la case Article 5 monitoring alors que l'on devrait avoir 1.
![registreuwwtpmonitoring](https://cloud.githubusercontent.com/assets/16286544/11871000/ac3d07d4-a4cc-11e5-9632-e401cb4d3327.PNG)

**Comment by bbondier** [comment]
Last modification to the algorithm removed all "Treatment required : other" cases in LT, this bug can't be reproduced anymore. If thise case appears in another country, please reopen this issue.
