### ISSUE TITLE
REGISTRE AGGLO comparison previous information Ireland

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#59]
Rappel général dans le document pourcentage avec une seule décimale.

Lorsque l'on est à moins de 20% et pas de changement de seuil ne pas mettre d'orange dans la case. 

Pour le calcul du pourcentage on prend l'évolution par rapport à la dernière situation. C'ets l'inverse qui est calculé ici

On doit avoir le ratio suivant: 
percent = generated load current/old generated load -1

ce qui donnerait pour Kilbeggan 2005/1800-1 = +11.4% 

![registre agglo comparison previous](https://cloud.githubusercontent.com/assets/16286544/11871396/a0beea3c-a4cf-11e5-9c2e-bdf1f558b2cb.PNG)

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
