### ISSUE TITLE
REGISTRE AGGLO notes de bas de page

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#60]
les notes 2 à 11 peuvent être supprimées des intitulés car c'était seulement pour donner les régles de calcul

La note (1) peut être remplacé par 

(1) if more than 20% or change of the requirements (e.g. 10 000 p.e. in a sa), the color of the cell is orange

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
