### ISSUE TITLE
REGSITRE AGGLO totaux pourcentage

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#61]
Attention pour les totaux finaux. On n'ajoute pas des pourcentage. On recalcule le pourcentage avec les valeurs données dans les totaux.

![regsitre agglo totaux pourcentage](https://cloud.githubusercontent.com/assets/16286544/11871541/8833c93c-a4d0-11e5-9668-54656ef95ae8.PNG)

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
