### ISSUE TITLE
REGISTRE AGGLO Conformité article 4 hierarchical approach

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#62]
Attention il y a une erreur dans le tableau. On calcul la hierarchical approach en pregnant la conformité Article 3 et la conformité Article 4. Si l'un des deux est non conforme c'est non conforme. Ce n'est pas le cas dans le fichier irlandais

![registre agglo conformite article 4](https://cloud.githubusercontent.com/assets/16286544/11871695/6fc8e12e-a4d1-11e5-8d1b-1b96f5625a2f.PNG)

**Comment by bbondier** [comment]
Fixed
