### ISSUE TITLE
REGISTRE AGGLO calcul des charges entrantes

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#63]
Attention il semblerait qu'il y ait un pb de calcul de charges entrantes

Sur l'agglo j'ai le sentiment que le calcul est fait non pas à partir de la charge total de l'agglo sur laquelle on applique le pourcentage de la table UwwtpAgglo mais plutôt que ce ratio est appliqué sur la charge connectée

Si on prend le cas de nicosie on a dans le schema de synthèse des p.e. qui ne sont pas cohérents avec la charge entrante dans la station

Par exemple Nicosia agglo

http://uwwtd.oieau.fr/cyprus/agglomeration/cy11-agglo/2011

et mia mia station

http://uwwtd.oieau.fr/cyprus/treatment-plant/cy11_1_uwwtp/2011

Dans le premier cas on a 127 183 p.e. connecté et dans la fiche station on a 140 000 p.e. entrant alors que dans le fichier reporting on a bien 59.545% de la charge totale générée qui entre sur la station mia milia soit 140 000 p.e. coherent avec le chiffre rapporté dans la table station.

Du coup le ratio connected sur entering laisse apparaitre un écart alors qu'en réalité tout est connecté. 

IL faut donc revoir les calculs sur les fiches individuels en pregnant bien le ratio de la table UwwtpAgglo par rapport à la charge entrante

![shema nicosia](https://cloud.githubusercontent.com/assets/16286544/11872395/43c88ff8-a4d5-11e5-90b3-c39fc869b56e.PNG)

**Comment by evincentoieau** [comment]
Effectivement, on applique le pourcentage de la table UwwtpAgglo sur la charge connectée. Le dictionnaire de données  peut être compris comme ça.
"aucPercEnteringUWWTP	Insert % of load of agglomeration collected in collecting system and entering that treatment plant
"

J'ai corrigé partout pour qu'on applique le pourcentage de la table UwwtpAgglo sur la charge totale générée de l'agglomération.

fait mais pas encore en production.
