### ISSUE TITLE
REGISTRE AGGLO distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#64]
Dans le cas Irlandais avec l'agglo de Shanganagh pourquoi distance to compliance est vide au niveau de l'article 4 alors que c'est NC article 4

![registre agglo shanganag](https://cloud.githubusercontent.com/assets/16286544/11873419/c6508098-a4da-11e5-85c2-99d316b87f67.PNG)

**Comment by bbondier** [comment]
Duplicate with #65
