### ISSUE TITLE
REGISTRE AGGLO distance to compliance IE

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#65]
Dans le cas irlandais pour l'agglomération de Shanganagh les champs distance to compliance devraient être rempli pour le traitement mais pas pour les performance.

IL faut utiliser les infos de UWWTP compliance "Compliance of treatment plant under expired and pending deadline"

Pour Passage/mo,kstown, Lusk, Ringaskiddy en plus des performances qui ne sont pas bonnes on devrait avoir le traitement qui n'est pas bon.

![registre agglo distance to compliance](https://cloud.githubusercontent.com/assets/16286544/11891901/64f60618-a563-11e5-96ed-565361aa411a.PNG)

**Comment by bbondier** [comment]
Fixed
