### ISSUE TITLE
REGISTRE UWWTP IE WEXFORD TOWN

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#66]
Pourquoi une non conformité traitement pour l'article 4 alors qu'il est declaré
![registreuwwtpwexfordtown](https://cloud.githubusercontent.com/assets/16286544/11892099/51a50508-a565-11e5-9ac8-27d3601a2198.PNG)
 un traitement secondaire.

Dans le cas de cette agglo c'est seulement le traitement de l'azote Article 5 qui est concerné.

**Comment by bbondier** [comment]
Fixed
