### ISSUE TITLE
REGISTER AGGLO compliance Article 5

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#68]
Il y a des problèmes de remplissage des champs conformités de l'Article 5

D'une part on doit avoir NR dans les cases conformités avec sans approche hiérarchique lorsque c'est NR

D'autre part on ne pas avoir NC sur 5b ou 5c quand l'article ne s'applique pas.

Au niveau du 5a quand les données fournies montrent que c'est non conforme on doit être NC en approche non hiérarchique et bien sûr en approche hériérarchique

![registeraggloarticle5compliance](https://cloud.githubusercontent.com/assets/16286544/11893356/4fd8f9ae-a570-11e5-9fd7-718f58eb267f.PNG)

**Comment by bbondier** [comment]
Fixed

**Comment by friboben** [comment]
Not completely because if one hierarchical approach art5 is PD, then the last column hierarchical approach is PD, it can not be NC.
