### ISSUE TITLE
Bug ergonomique fleche clavier & Pg UP, Pg UP

### ISSUE THREAD

**Issue by lcrespin** [OIEau/uwwtd#7]
Vu en Roumanie

Sur une page avec une carte, l'utilisation des flèches du clavier ou de Page up & Page down déplace la carte et pas la page. Du coup on est obligé de faire avec l'ascenceur à la souris.

**Comment by ndhuygelaere** [comment]
Le bug n'est plus visible sur la version actuelle du site. Il est possible que control "Keyboard Controls" ait été la cause de ce problème
