### ISSUE TITLE
REGISTRE AGGLO receiving water IE

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#70]
Attention au niveau des champs receiving water de l'agglo ils doivent remplis meme pour des zones non sensibles et dans type of receiving water on a dans la plupart des cas NA

Il faut de plus supprimer les sigles et les remplacer par les expressions

![registre agglo ie receiving area](https://cloud.githubusercontent.com/assets/16286544/11893524/9d8f1be6-a571-11e5-930a-49facc3058f0.PNG)

**Comment by bbondier** [comment]
Fixed
