### ISSUE TITLE
REGISTRE AGGLO Chypre compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#71]
Dans le cas de Chypre on a des 7 dans les colonnes ce qui est pour le moins étrange. Il faut revoir toute cette partie sur les registres avec distance to compliance

![registre agglo chypre compliance](https://cloud.githubusercontent.com/assets/16286544/11893586/0d68c75a-a572-11e5-9368-bffe9cd92b36.PNG)

**Comment by bbondier** [comment]
There is a '7' case in the algorithm. This has been defined by UBA but we have no idea of what it is supposed to represent. Closing for now.

**Comment by Rakedjian** [comment]
What about UBA answer on that it is the first time I have heard about that. Please let me know in which algorithm it is

**Comment by bbondier** [comment]
Here is the algorithm we have for those columns :

`// =IF(’% of generated load for which compliance with Art. 5a/5b/5c is not relevant’>0;
//     "NR";
//     IF(AND(‘deadline for agglomeration’<=reference date of reporting; 
//            ’% of generated load not compliant with Art. 5a/5b/5c’=0; 
//            ’% of generated load for which compliance with Art. 5a/5b/5c  is not relevant’=0);
//         "C";
//         IF(AND(‘deadline for agglomeration’<=reference date of reporting; 
//                ’% of generated load for which compliance with Art. 5a/5b/5c  is not relevant’=0;
//                (AND(
//                      AND(’% of generated load not compliant with Art. 5a/5b/5c’>0; 
//                         ’% of collected load not compliant with Art. 5a/5b/5c’<=1
//                         ); 
//                      ’p.e. not compliant with Art. 5a/5b/5c’<2000))
//                );
//                "C";
//                IF(AND(‘deadline for agglomeration’<=reference date of reporting; 
//                       ’% of generated load for which compliance with Art. 5a/5b/5c  is not relevant’=0;
//                       (OR(’% of generated load not compliant with Art. 5a/5b/5c’>1; 
//                           ’p.e. not compliant with Art. 5a/5b/5c’>=2000))
//                      );
//                      "NC";
//                      7))))   `

**Comment by bbondier** [comment]
![image](https://cloud.githubusercontent.com/assets/15143612/13566564/7e8c5974-e456-11e5-9ec0-26220d4f1784.png)

Here is the algorithm we have for these columns. This is coming from the "Detailed description of the assessment methodology in the excel-registers" document, page 34 & 36.

**Comment by Rakedjian** [comment]
I thing that this is  mistake. There is no reason to have 7.
