### ISSUE TITLE
REGISTRE AGGLO installation in place

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#72]
Revoir les calculs pour que cela soit concordant avec le precedent questionnaires. Dans le cas Irlandais voice un extrait du register généré par le site puis du register original

![registre agglo installation in place new](https://cloud.githubusercontent.com/assets/16286544/11893928/4b9cbe62-a574-11e5-8e16-51293979ddc8.PNG)

![registre agglo installation in place old](https://cloud.githubusercontent.com/assets/16286544/11893934/589eb7fa-a574-11e5-8247-85ef1684f9d1.PNG)

**Comment by bbondier** [comment]
Most of the calculations seems to be corrected. However, missing datas in some stations (ex: Ringsend) cause troubles. We're currently raising an error when those datas are missing during the import of the xml files.
