### ISSUE TITLE
SITE IRLANDAIS BUG FICHES STATIONS

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#73]
les fiches stations n'apparaissent pas lorsque l'on clique d'une agglo vers la station

Par exemple Shanganagh on arrive sur la page suivante

![bug site irlandais](https://cloud.githubusercontent.com/assets/16286544/11893879/fffeaf60-a573-11e5-9173-6a83a7c2fc76.PNG)

**Comment by ndhuygelaere** [comment]
il y avait une erreur dans un appel de fonction, c'est corrigé
