### ISSUE TITLE
REGISTRE Summary legal compliance Article 4

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#74]
Revoir les calculs pour l'article 4

Voici le cas irlandais où il n'y a aucune nouvelle conformité avec le nouveau register alors que dans l'ancien ce n'était pas le cas et la réalité c'est qu'il y a des non conformités article 4. C'est peut être en lien avec la Remarque déjà faite sur les informations indiqués dans le Feuillet AGGLO.

register généré automatiquement

![registre official compliance article 4new](https://cloud.githubusercontent.com/assets/16286544/11894064/06affaca-a575-11e5-9441-97b676b6123e.PNG)

Registre original

![registre official compliance article 4 old](https://cloud.githubusercontent.com/assets/16286544/11894078/1f4c3f12-a575-11e5-9258-7449c45e66f0.PNG)

**Comment by bbondier** [comment]
Fixed
