### ISSUE TITLE
REGISTRE summary legal compliance Article 5 IE

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#75]
Revoir le calcul pour l'article 5

Dans le cas Irlandais on a beaucoup d'agglos qui ne sont pas concernées dû à la taille inférieure à 10 000 et il y a deux agglos de difference dans le total et également des agglos qui rejettent en zones normales dont il faut faire figurer le nombre et la charge correspondante

En ce qui concerne le nombre d'agglomérations sous 10 000 eh il y a en bien 105. Les 10 000 juste sont à compter dans la liste car la directive parle de > 10 000 pour la zone sensible.

Par contre cela n'explique que la difference de 1 pas de 2.

register généré

![registre summary compliance article 5 new](https://cloud.githubusercontent.com/assets/16286544/11894764/af93ebf2-a579-11e5-91d1-f3e799aa6598.PNG)

register d'origine

![registre summary compliance article 5 old](https://cloud.githubusercontent.com/assets/16286544/11894769/b9b2cb58-a579-11e5-81ba-36e712c46bb1.PNG)

**Comment by bbondier** [comment]
Fixed. However, there is still an agglomeration missing in "Article 5 - Actual" (Wexford Town). This agglomeration appears not compliant in our register due to the missing "Nitrate" field in the data model for Ireland.
