### ISSUE TITLE
REGISTRE distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#77]
Les informations du tableau distance to compliance doivent être cohérentes avec le total des champs correspondants dans le Feuillet agglo corrigé.

Attention pourcentage avec un chiffre après la virgule

Dans l'exemple ci dessous au niveau de l'Irlande pour target connecte c''est 0 en pourcentage, les chiffres secondary treatment sont à corriger et il faut ajouter les données pour more stringent treatment

![registre distance to compliance](https://cloud.githubusercontent.com/assets/16286544/11895105/0ba5e60a-a57c-11e5-8901-374fdc6807c6.PNG)

Si on prend la lithuanie on a toutes les stations qui sont conformes en traitement secondaire donc one doit avoir zero pour distance to compliance pour ce type de traitement. L'erreur semble venir du calcul au niveau de la charge connectée et la charge entrante qui génère une fuite dans le réseau alors qu'il n'y en a pas.

**Comment by friboben** [comment]
partially:
- still to be added cells D12 (=sum D13+D14), D32 (=sum D33+D34), D51 (=sum D52+D53)
- correction for cells E12: =100-D12 E32=100-D32 E51=100-D51
E17, E18 include condition C16>0
E21, E22 include condition C20>0
E37, E38 include condition C36>0 
E41, E42 include condition C40>0
E56, E57 include condition C55>0
E60, E61 include condition C59>0

**Comment by Yasham** [comment]
Fixed

**Comment by bbondier** [comment]
Fixed
