### ISSUE TITLE
Taurange

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#78]
Attention ici en Lithuanie, avec l'agglo TAURAGE on a un bon exemple d'erreur de calcul au niveau de la charge connectée et la charge entrante déjà signalée.

http://uwwtd.oieau.fr/lithuania/treatment-plant/lt-ag-017-wwtp-01/2011

Si on ouvre le fichier XML pour Taurange on a un pourcentage de la charge générée de la taille agglo qui est de 88,5% et la charge entrante declare à 37170 une coherence totale alors que dans le register on considère une partie de la charge connectée non traitée avec l'erreur de calcul ce qui génère une non conformité article 4

Il y a quand meme un souci de calcul sur le site car avec une partie de la charge connectée non traitée on a une non conformité Article 4 qui n'apparait pas telle quelle dans le site

![taurage agglo](https://cloud.githubusercontent.com/assets/16286544/11895392/96f44c86-a57e-11e5-8cd9-45f245c25059.PNG)

![taurage secondary treatment compliance](https://cloud.githubusercontent.com/assets/16286544/11895397/9dde8d40-a57e-11e5-8a99-ae1e207ddfc8.PNG)
 On a aussi la contradiction avec distance to compliance car si vraiment une partie de la charge n'était pas traitée on aurait aussi distance to compliance correspondant uniquement à cette charge en rouge dans traitement et performance pour le secondary treatment et bien sûr en repercussion sur more stringent treatment.

![taurage distance to compliance](https://cloud.githubusercontent.com/assets/16286544/11895433/03e25ae0-a57f-11e5-8b40-d0ced06d1acb.PNG)

**Comment by friboben** [comment]
problème corrigé, voir ici: http://webnuxdev.rnde.tm.fr/uwwtd_lt/treatment-plant/lt-ag-017-wwtp-01/2011
l'affichage du schéma est corrigé et sera mis à jour avec la prochaine mise à jour.

**Comment by bbondier** [comment]
Fixed
