### ISSUE TITLE
REGISTER breach list

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#79]
Revoir les breach list

Incoherence entre ce qui sort dans le nouveau register et ce qui est dans l'ancien

IE générée automatiquement

![registre breach list ie new](https://cloud.githubusercontent.com/assets/16286544/11896882/9d3a5980-a58a-11e5-98f2-5475662e81db.PNG)

IE  originale

![registre breach list ie original](https://cloud.githubusercontent.com/assets/16286544/11896890/abe1185c-a58a-11e5-840b-61d16b6d5834.PNG)

LT new

![registre bl lt new](https://cloud.githubusercontent.com/assets/16286544/11896923/033e64ec-a58b-11e5-915a-d99232f6ece8.PNG)

LT original

![registre bl lt old](https://cloud.githubusercontent.com/assets/16286544/11896926/0bc681f8-a58b-11e5-86af-2391de1042bc.PNG)

CY new
![registre bl cy new](https://cloud.githubusercontent.com/assets/16286544/11896946/486daf96-a58b-11e5-8772-f5d8888b70b4.PNG)

CY original

![registre bl cy old](https://cloud.githubusercontent.com/assets/16286544/11896954/51d0b010-a58b-11e5-9ebe-dbc5bf641575.PNG)

**Comment by bbondier** [comment]
Fixed
