### ISSUE TITLE
REGISTER BIG CITY

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#80]
revoir le calcul du pourcentage par rapport au meilleur traitement. Surement en lien avec les pb de calcul de charge connectée et entrante déjà signalé

![registre summary big city](https://cloud.githubusercontent.com/assets/16286544/11897064/8f9e4c1c-a58c-11e5-9e73-75361c21b7e5.PNG)

**Comment by friboben** [comment]
In the example of Kaunas, http://uwwtd.oieau.fr/lithuania/agglomeration/lt-ag-002/2011 90% is connected to collecting system but when using the table agglo-uww the percentage of load entering the station is lower (see on scheme load entering is about 212000) this leads to reduction (probably release during transport), hence final value is about 80% of generated load and as TP has treatment on NP and other (http://uwwtd.oieau.fr/lithuania/treatment-plant/lt-ag-002-wwtp-01/2011) it is not possible to decide which is higher and both are made visible. Please clarify what you want and possible misinterpretation in above explanation.

**Comment by Rakedjian** [comment]
There is a real issue because we have in the reporting tables two load entering. Firstly the percentage in the UwwtdAgglo table and secondly the load entering in p.e. declared in the UWWTp table. 

I have asked MS to check the coherence of both information to avoid inconsistencies. 

I prefer to use only the load entering the treatment plant in the website. It means in the picture and also in the UWWTP fiche. 

I think that for the calculation of compliance we use the rate. Don't change anything for the calculation of compliance. 

The website will help us to identify better these inconsistencies.

**Comment by friboben** [comment]
The information in the table UwwtdAgglo is of particular use when more than one agglomeration is connected to one treatment plant, else it is not possible to know which part of the load entering the plant comes from which agglomeration. Some inconsistencies are detected like an obvious one for Ljubjana where load entering in the TP fiche is higher than sum of loads from all agglo connected (and even higher than  the design capacity: comes from xml but we have introduced a quality control in importing tool to allow admin to identify this.

**Comment by Rakedjian** [comment]
yes you are right. Do your best. In the future I would like not allow again having several agglomerations attached to one treatment plant.
Normally the website will help to the coherence of all the information.

**Comment by bbondier** [comment]
Should we do something or leave it as it is ? Reopen if needed.

**Comment by Rakedjian** [comment]
It is ok but we have to keep it in mind

**Comment by friboben** [comment]
Overall we should also keep in mind if data are correctly entered, the difference between the load entering in collecting system and best treatment is what is lost in network. In last version of register the above figures are 89%, hence as in scheme on website, ie 1% is lost during transport: an interesting info.
