### ISSUE TITLE
NUTS2 analyse

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#81]
Revoir calcul notamment pour Irlande Article 4 et Article 5

![registre nuts2 new](https://cloud.githubusercontent.com/assets/16286544/11897202/f2c3f764-a58d-11e5-83b5-afece09605a7.PNG)

**Comment by friboben** [comment]
problème identifié (feuille agglo), en cours de correction

**Comment by bbondier** [comment]
Fixed

**Comment by friboben** [comment]
overall the NUTS 2 corresponds to macroregion. In slovenia it is in fact the whole country (see https://en.wikipedia.org/wiki/NUTS_of_Slovenia), hence the dedicated nuts 2 table gives summary figure for the country.
