### ISSUE TITLE
REGISTRE GRAPH percentage of removal

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#82]
Remarque déjà faite au niveau des fiches stations. Revoir le calcul. Dans un cas comme l'Irlande qui n'a fourni aucune données on ne peut pas avoir 100% d'élimiation pour tous les paramètres. 

![registre graphpercentage removal](https://cloud.githubusercontent.com/assets/16286544/11898089/83725e20-a595-11e5-9faf-71cb266fe20a.PNG)

**Comment by bbondier** [comment]
Fixed.
