### ISSUE TITLE
REGISTRE GRAPH agglo size

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#83]
Attention dans les graphs les agglos de 2000 Eh et de 10 000 Eh sont comprises dans les 2000 -10000 Eh. 

Les agglos de 100 000 sont comprises dans les 10 001- 100 000 p.e.

Les tableaux sont donc à corriger

![registre graph agglo size](https://cloud.githubusercontent.com/assets/16286544/11898386/cb809c16-a597-11e5-87a4-d91e51d89b30.PNG)

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
