### ISSUE TITLE
REGISTRE GRAPH total design capacity

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#84]
Tous les nombres dans ce tableau ne doivent avoir aucune décimale

Attention aux pays où il y a plusieurs agglos rattachées à la meme station.
 Il ne faut pas sommer les capacities de toutes les stations car on risqué de les compter deux fois. Il faut donc éliminer les doublons dans ce calcul

Pour Chypre par exemple on obtiendrait 2 600 700 Eh en comptant de nombreuses fois les memes stations

![registre graph total design capacity](https://cloud.githubusercontent.com/assets/16286544/11898557/e057b1fa-a598-11e5-925a-0e7d7d8bb5b2.PNG)

**Comment by friboben** [comment]
counted at level of agglomeration: total generated load, collecting load, IAS
possible double count at level of uwwtp:
1. on total design capacity: need to consider sheet UWWTP level column capacity (column U) and group by UWWTP code (column N)
2. on entering load: need to consider sheet UWWTP level column entering load calculated (UwwtpAgglo) (column R) and group by UWWTP code (column N)

**Comment by bbondier** [comment]
Fixed
