### ISSUE TITLE
REGISTRE GRAPH percentage of reuse

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#85]
Mettre une décimale après la virgule au niveau du pourcentage. Il y a des pays qui ont des valeurs inférieures à 1.

![registre graph percentage reuse](https://cloud.githubusercontent.com/assets/16286544/11900201/82bc5e72-a5a4-11e5-9f1f-002b3a72b4fb.PNG)

**Comment by bbondier** [comment]
This value comes directly from the XML file, nothing we can do about formatting.
