### ISSUE TITLE
REGISTRE GRAPH compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#86]
Faire en sorte que les résultats automatiquement générés soient cohérents avec ce qui a été calculé dans le register original au niveau C et NC. Attention ce tableau reflette la conformité officielle? On ne peut donc avoir plus de 4 agglomerations pour Chypre car il n'y a que ce qui est concerné par expired deadlines

tableau généré avec le site

![registre graph compliance new](https://cloud.githubusercontent.com/assets/16286544/11900365/ce9e1d52-a5a5-11e5-9b38-daecbc9ee304.PNG)

Ancien tableau
![registre graph compliance per article](https://cloud.githubusercontent.com/assets/16286544/11900394/ee675dc4-a5a5-11e5-9599-bf9edf586e20.PNG)

**Comment by friboben** [comment]
Ici on a considéré tout ce qui était compliant référencé comme tel: tu veux seulement ce qui est expired?

**Comment by Rakedjian** [comment]
It is not possible to have that in 2011 because in Cyprus there were only 4 agglomerations concerned by Article 3 and 4 compliance calculation and two concerned by  Article 5.

**Comment by friboben** [comment]
On website we show compliant agglomerations even if the deadline is not expired: the same logic was applied here, we will correct the calculation according your view, ie only expired, ie for CY only 4 agglomerations.

**Comment by Rakedjian** [comment]
For the official compliance calculation under expired deadline we only have to take into account the related agglomerations even if more agglomerations are compliant. It is of course different with countries like POland and Romania where we have to calculate a rate of the load. It ishere relevant to take into account all the agglomerations. I think that with Poland and Roumania we will use for official compliance assessment the distance to compliance table. No need to adapt the register to some of the countries.

**Comment by friboben** [comment]
exclude PD from calculation of sums
