### ISSUE TITLE
REGISTRE AGGLO CY expired deadlines

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#87]
Attention paphos a des dates d'échéances au 31/12/2011 donc fait partie des expired deadlines

![registre agglo expired deadlines](https://cloud.githubusercontent.com/assets/16286544/11900521/c9ca4598-a5a6-11e5-9cb3-cd49922d990b.PNG)

**Comment by evincentoieau** [comment]
Oui, il y avait une erreur

fait mais pas encore en production.
