### ISSUE TITLE
REGISTRE CY Summarize legal compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#88]
Attention ces tableaux ne concernent que des calculs d'agglomérations qui sont en pending deadlines. A chypre on a 4 agglomerations concernées

![registre cy summary legal compliance](https://cloud.githubusercontent.com/assets/16286544/11900580/2b6e82dc-a5a7-11e5-8e86-d3795cd3d61a.PNG)

**Comment by friboben** [comment]
Je ne comprends pas la remarque: le tableau en copie est celui de la feuille Summary_legal_compliance qui donne la compliance pour le territoire, pas la distance to compliance: tu pourrais préciser ta remarque? Merci.

**Comment by Rakedjian** [comment]
In 2011 we have in Cyprus 4 agglomerations concerned by expired deadlines and not 13-15. It is also strange tohave more agglomerations concerned by article 4 than by Article 3.

See below the old register

![compliancecy](https://cloud.githubusercontent.com/assets/16286544/12583176/b4025bf6-c441-11e5-9780-7966ef3d60af.PNG)
