### ISSUE TITLE
REGISTRE GRAPH compliance graph

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#89]
revoir les calcul au niveau des tableaux qui servent à produire les graphs de compliance pour C et NC.

nouveau tableau
![registre graph ie compliance graph new](https://cloud.githubusercontent.com/assets/16286544/11900811/67fc71fe-a5a8-11e5-9fad-a82529db630e.PNG)

Tableaux d'origine

![registre graph compliance graph](https://cloud.githubusercontent.com/assets/16286544/11900770/3b133ad8-a5a8-11e5-9529-4c4ba335accb.PNG)

**Comment by friboben** [comment]
Ici on touche au fait que l'UBA avait effectué un certain nombre d'opérations manuelles d'interprétation des données fournies qui ne peuvent pas être automatisées. Pour 2012 les 28000 en tertiary correspondent à l'agglomeration de wexford http://webnuxdev.rnde.tm.fr/nd_uwwtd_si/agglomeration/ieag_526/2012
le xml ne contient pas l'info N removal et seul le champ texte uwwspecification indique biological treatment N & P. Ce champ peut contenir n'importe quoi, on ne peut donc pas automatiser un traitement. Pour 2010 on a le même problème: IE n'a pas fourni le champ <NRemoval> mais en plus le champ % of load entering de la table uwwagglo est non renseigné, les algorithmes donnent donc un résultat "no information" qui n'est pas remonté dans le tableau du registre. Dans ce cas précis UBA avait utilisé le champ load entering de la table uwwtp pour calculer la compliance, ce qui est possible pour IE car on a une agglo -->une station. Pour la plateforme SIIF cela imposerait de modifier encore les algorithmes pour ajouter une règle de calcul pour chaque agglo de type: si j'ai nb de stations de l'agglo = 1 j'utilise le champ load entering de la table uwwtp, sinon j'utilise load collected in collecting system x % of load entering the uwwtp.

**Comment by Rakedjian** [comment]
Je vois mal que l'on ne puisse pas fournir l'information puisque l'on a la donnée de compliance pour chaque agglo. 

Par exemple sur l'article 4 on ne peut pas avoir une conformité totale puisque lorsque je fais le tri des agglos non conformes sur l'article 4 j'en ai une trentaine qui ressort avec une charge de plusieurs milliers d'EH.

**Comment by friboben** [comment]
fixed
