### ISSUE TITLE
REGISTRE GRAPH installation in place

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#90]
Revoir les calculs et render cohérents avec ce qui est dans le register precedent.

table générée automatiquement
![registre graph installation in place new](https://cloud.githubusercontent.com/assets/16286544/11901158/5b4e0790-a5aa-11e5-9d96-d0ccd5e920a5.PNG)

Table de l'ancien registre
![registre graph instlation in place](https://cloud.githubusercontent.com/assets/16286544/11901195/8283a158-a5aa-11e5-9228-fa07571b4960.PNG)

**Comment by bbondier** [comment]
Has been fixed in a new update.
