### ISSUE TITLE
REGISTRE GRAPH distance to compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#91]
Revoir le calcul des tables dans le cas irlandais on ne peut avoir 100% pour tout en distance to compliance. la distance t ocompliance c'est ce qui reste. 

![registre graph distance to compliance](https://cloud.githubusercontent.com/assets/16286544/11901252/d7f53548-a5aa-11e5-93d0-305cf7a05130.PNG)

**Comment by friboben** [comment]
correct cells
B89 if (c89<1;c89/b88x100;0)
B105 if (c105<1;c105/b104x100;0)
B110 if (c110<1;c110/b109x100;0)
B111 if (c111<1;c111/b110x100;0)
B120 if (c120<1;c120/b119x100;0)

**Comment by bbondier** [comment]
Fixed
