### ISSUE TITLE
REGISTRE GRAPH load concentration

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#92]
pour les deux dernieres paramètres de la table en charge en t/y remplacer mg/l par t/y

![registre graph load](https://cloud.githubusercontent.com/assets/16286544/11901334/665ec93e-a5ab-11e5-9e3a-44a4c7da0362.PNG)

Pour les six premiers paramètres de concentration  remplacer t/y par mg/l

![registre graph concentration](https://cloud.githubusercontent.com/assets/16286544/11901387/9c8aadac-a5ab-11e5-81f5-3dab8a8ddb0f.PNG)

**Comment by evincentoieau** [comment]
fait mais pas encore en production.
